"""API总路由注册"""
from fastapi import APIRouter
from app.api.v1 import auth, dashboard, sync, task, finance, kingdee_finance, finance_center, finance_v2, mumaren_finance_center, mumaren_finance_center_domains, mumaren_finance_center_crud, ai, ai_assistant, ai_diagnosis, dingtalk, system, etl, rules, report, acceptance, audit, baison, dingtalk_finance, hr, store, product, inventory, member, mobile, life_data, life_data_analysis, investment_decision

api_router = APIRouter(prefix="/api/v1")

api_router.include_router(auth.router)
api_router.include_router(dashboard.router)
api_router.include_router(sync.router)
api_router.include_router(task.router)
api_router.include_router(finance.router)
api_router.include_router(kingdee_finance.router)
api_router.include_router(finance_center.router)
api_router.include_router(finance_v2.router)
api_router.include_router(mumaren_finance_center.router)
api_router.include_router(mumaren_finance_center_domains.router)
api_router.include_router(mumaren_finance_center_crud.router)
api_router.include_router(ai.router)
api_router.include_router(ai_assistant.router)
api_router.include_router(ai_diagnosis.router)
api_router.include_router(dingtalk.router)
api_router.include_router(system.router)
api_router.include_router(etl.router)
api_router.include_router(rules.router)
api_router.include_router(report.router)
api_router.include_router(acceptance.router)
api_router.include_router(audit.router)
api_router.include_router(baison.router)
api_router.include_router(store.router)
api_router.include_router(product.router)
api_router.include_router(inventory.router)
api_router.include_router(member.router)
api_router.include_router(dingtalk_finance.router)
api_router.include_router(hr.router)
api_router.include_router(mobile.router)
api_router.include_router(life_data.router)
api_router.include_router(life_data_analysis.router)
api_router.include_router(investment_decision.router)
