import request from "./request";

export const systemApi = {
  getUsers: (params?: any) => request.get("/system/users", { params }),
  createUser: (data: any) => request.post("/system/users", data),
  updateUser: (id: number, data: any) => request.put(`/system/users/${id}`, data),
  deleteUser: (id: number) => request.delete(`/system/users/${id}`),
  enableUser: (id: number) => request.post(`/system/users/${id}/enable`),
  disableUser: (id: number) => request.post(`/system/users/${id}/disable`),
  resetUserPassword: (id: number, data?: any) => request.post(`/system/users/${id}/reset-password`, data || {}),
  getRoles: (params?: any) => request.get("/system/roles", { params }),
  getRoleDetail: (id: number) => request.get(`/system/roles/${id}`),
  createRole: (data: any) => request.post("/system/roles", data),
  updateRole: (id: number, data: any) => request.put(`/system/roles/${id}`, data),
  deleteRole: (id: number) => request.delete(`/system/roles/${id}`),
  getRolePermissions: (id: number) => request.get(`/system/roles/${id}/permissions`),
  updateRolePermissions: (id: number, data: any) => request.put(`/system/roles/${id}/permissions`, data),
  updateRoleDataScope: (id: number, data: any) => request.put(`/system/roles/${id}/data-scope`, data),
  getParams: () => request.get("/system/params"),
  getModulePermissionMatrix: () => request.get("/system/permissions/module-matrix"),
  getRegisterApplications: (params?: any) => request.get("/system/register-applications", { params }),
  approveRegisterApplication: (id: string, data?: any) => request.post(`/system/register-applications/${id}/approve`, data || {}),
  rejectRegisterApplication: (id: string, data: any) => request.post(`/system/register-applications/${id}/reject`, data),
  getDataScopes: () => request.get("/system/data-scopes"),
  updateUserDataScope: (userId: number, data: any) => request.put(`/system/users/${userId}/data-scope`, data),
  getUserDataScopePreview: (userId: number) => request.get(`/system/users/${userId}/data-scope-preview`),
  getFieldPermissions: (params?: any) => request.get("/system/field-permissions", { params }),
  updateFieldPermissions: (data: any) => request.put("/system/field-permissions", data),
  getSecuritySettings: () => request.get("/system/security-settings"),
  updateSecuritySettings: (data: any) => request.put("/system/security-settings", data),
  getOperationLogs: (params?: any) => request.get("/system/operation-logs", { params }),
  getSystemDashboardStats: () => request.get("/system/dashboard-stats"),
  getOrgOptions: () => request.get("/system/org-options"),
};
