<template>
  <div class="page-container">
    <div class="page-header"><h2>利润分析</h2></div>
    <el-tabs v-model="activeTab" class="profit-analysis-page">
      <el-tab-pane label="利润分析" name="profit">
        <div class="profit-head"><div><b>经营利润</b><el-tag v-if="profitState === 'pending' || profitState === 'ready'" size="small" :type="profitState === 'ready' ? 'success' : 'warning'">{{ profit?.status_label }}</el-tag></div><span v-if="profitState === 'pending' || profitState === 'ready'" class="period">{{ profit?.period.start_date }} 至 {{ profit?.period.end_date }}</span><el-button size="small" :loading="profitState === 'loading'" @click="loadProfit">刷新</el-button></div>
        <div v-if="profitState === 'loading'" class="state-panel" v-loading="true" />
        <el-alert v-else-if="profitState === 'error'" :title="profitError" type="error" :closable="false" />
        <el-empty v-else-if="profitState === 'empty'" description="暂无利润数据" />
        <section v-else-if="profitState === 'pending' || profitState === 'ready'">
          <template v-if="profit">
            <div class="metric-grid"><div class="metric"><span>销售额</span><b>{{ money(profit.summary.net_sales) }}</b></div><div class="metric"><span>毛利额</span><b>{{ money(profit.summary.gross_profit) }}</b></div><div class="metric"><span>费用覆盖</span><b>{{ pct(profit.summary.expense_coverage_rate) }}</b></div><div class="metric"><span>标准进价覆盖</span><b>{{ pct(profit.summary.standard_purchase_price_coverage_rate) }}</b></div><div class="metric"><span>{{ profit.status === 'ready' ? '经营利润' : '经营利润（估算）' }}</span><b>{{ profit.summary.operating_profit == null ? '待接入' : money(profit.summary.operating_profit) }}</b></div></div>
            <h3>费用覆盖状态</h3><div class="expense-coverage-grid"><div v-for="item in profit.expense_coverage" :key="item.expense_type" class="expense-coverage"><span>{{ expenseTypeLabel(item.expense_type, item.label) }}</span><el-tag size="small" :type="item.status === 'ready' && item.approved ? 'success' : 'warning'">{{ expenseCoverageStatus(item) }}</el-tag></div></div>
            <div v-if="profit.missing_expense_types.length" class="pending-line">费用缺失：{{ profit.missing_expense_types.map((type) => expenseTypeLabel(type)).join('、') }}；经营利润为估算值</div>
            <h3>损失及库存资金</h3><div class="metric-grid loss-grid"><div class="metric"><span>折扣损失</span><b>{{ money(profit.summary.discount_loss) }}</b></div><div class="metric"><span>退货损失</span><b>{{ money(profit.summary.return_loss) }}</b></div><div class="metric"><span>清仓损失</span><b>{{ money(profit.summary.clearance_loss) }}</b></div><div class="metric"><span>库存资金</span><b>{{ money(profit.summary.inventory_amount) }}</b></div></div>
            <h3>门店利润</h3><el-table :data="profit.stores" size="small" stripe><el-table-column prop="store_name" label="门店" min-width="180" /><el-table-column label="销售额"><template #default="{ row }">{{ money(row.net_sales) }}</template></el-table-column><el-table-column label="毛利"><template #default="{ row }">{{ money(row.gross_profit) }}</template></el-table-column><el-table-column label="经营利润"><template #default="{ row }">{{ row.operating_profit == null ? '待接入' : money(row.operating_profit) }}</template></el-table-column></el-table>
            <h3>单款利润</h3><el-table :data="profit.products" size="small" stripe max-height="360"><el-table-column prop="product_code" label="款号" width="130" /><el-table-column prop="product_name" label="商品" min-width="180" /><el-table-column label="销售额"><template #default="{ row }">{{ money(row.net_sales) }}</template></el-table-column><el-table-column label="毛利"><template #default="{ row }">{{ money(row.gross_profit) }}</template></el-table-column><el-table-column label="经营利润"><template #default>待接入费用分摊</template></el-table-column></el-table>
          </template>
        </section>
      </el-tab-pane>
      <el-tab-pane v-if="canCreateExpense" label="费用补录" name="expense"><el-card><el-form :model="expenseForm" label-width="110px" style="max-width:560px"><el-form-item label="费用日期" required><el-date-picker v-model="expenseForm.expense_date" type="date" value-format="YYYY-MM-DD" style="width:100%" /></el-form-item><el-form-item label="关联门店"><el-input v-model="expenseForm.store_code" placeholder="留空=公司级费用" /></el-form-item><el-form-item label="费用类型" required><el-select v-model="expenseForm.expense_type" style="width:100%"><el-option label="租金" value="rent" /><el-option label="工资" value="wages" /><el-option label="社保" value="social_security" /><el-option label="平台费" value="platform_fee" /><el-option label="水电" value="utilities" /><el-option label="物流" value="logistics" /><el-option label="营销" value="marketing" /><el-option label="其他" value="other" /></el-select></el-form-item><el-form-item label="费用金额" required><el-input-number v-model="expenseForm.expense_amount" :min="0.01" :precision="2" style="width:100%" /></el-form-item><el-form-item label="数据状态">预估值（提交后由财务独立核准）</el-form-item><el-form-item label="备注"><el-input v-model="expenseForm.description" type="textarea" :rows="2" /></el-form-item><el-form-item><el-button type="primary" :loading="submitting" @click="submitExpense">提交录入</el-button></el-form-item></el-form></el-card></el-tab-pane>
      <el-tab-pane v-if="canCreateCash" label="现金补录" name="cash"><el-card><el-form :model="cashForm" label-width="110px" style="max-width:560px"><el-form-item label="记录日期" required><el-date-picker v-model="cashForm.record_date" type="date" value-format="YYYY-MM-DD" style="width:100%" /></el-form-item><el-form-item label="账户类型"><el-select v-model="cashForm.account_type" style="width:100%"><el-option label="银行账户" value="bank" /><el-option label="现金" value="cash" /></el-select></el-form-item><el-form-item label="账户名称"><el-input v-model="cashForm.account_name" /></el-form-item><el-form-item label="余额" required><el-input-number v-model="cashForm.balance" :precision="2" style="width:100%" /></el-form-item><el-form-item label="是否核准"><el-switch v-model="cashForm.data_type" active-value="actual" inactive-value="estimate" active-text="已财务核准" inactive-text="待核准" /></el-form-item><el-form-item><el-button type="primary" :loading="submitting" @click="submitCash">提交录入</el-button></el-form-item></el-form></el-card></el-tab-pane>
      <el-tab-pane v-if="canViewCash" label="现金安全天数" name="cash_safety"><el-card><div v-if="cashState === 'loading'" class="state-panel" v-loading="true" /><el-alert v-else-if="cashState === 'error'" :title="cashError" type="error" :closable="false" /><el-empty v-else-if="cashState === 'empty'" description="暂无现金数据，请先补录" /><div v-else-if="cashState === 'ready' && cashSafety"><div class="cash-cards"><div class="cash-card"><span>现金余额合计</span><b>{{ money(cashSafety.total_cash_balance) }}</b></div><div class="cash-card"><span>日均支出（近30天）</span><b>{{ money(cashSafety.daily_avg_expense_30d) }}</b></div><div class="cash-card"><span>现金安全天数</span><b>{{ cashSafety.cash_safety_days == null ? '--' : cashSafety.cash_safety_days + '天' }}</b></div><div class="cash-card"><span>风险等级</span><el-tag :type="cashRiskType(cashSafety.risk_level)">{{ cashRiskLabel(cashSafety.risk_level) }}</el-tag></div></div><p class="cash-note">{{ cashSafety.note }}</p></div><el-button size="small" class="refresh-button" :loading="cashState === 'loading'" @click="loadCashSafety">刷新</el-button></el-card></el-tab-pane>
      <el-tab-pane label="每日利润状态" name="daily_status"><el-card><div v-if="dailyState === 'loading'" class="state-panel" v-loading="true" /><el-alert v-else-if="dailyState === 'error'" :title="dailyError" type="error" :closable="false" /><el-empty v-else-if="dailyState === 'empty'" description="暂无每日利润数据" /><el-table v-else-if="dailyState === 'ready'" :data="dailyItems" stripe size="small"><el-table-column prop="stat_date" label="日期" width="120" /><el-table-column label="销售额"><template #default="{ row }">{{ money(row.net_sales) }}</template></el-table-column><el-table-column label="毛利"><template #default="{ row }">{{ money(row.gross_profit) }}</template></el-table-column><el-table-column label="经营利润"><template #default="{ row }">{{ row.operating_profit == null ? '待接入' : money(row.operating_profit) }}</template></el-table-column><el-table-column label="数据类型"><template #default="{ row }">{{ row.data_type_label || dataTypeLabel(row.data_type) }}</template></el-table-column><el-table-column label="状态"><template #default="{ row }"><el-tag size="small" :type="row.status === 'ready' ? 'success' : 'warning'">{{ dailyStatusLabel(row.status) }}</el-tag></template></el-table-column></el-table><el-button size="small" class="refresh-button" :loading="dailyState === 'loading'" @click="loadDaily">刷新</el-button></el-card></el-tab-pane>
    </el-tabs>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import { ElMessage } from "element-plus";
import { financeApi, type CashSafety, type ExpenseType, type FinanceDataType, type ManualCashPayload, type ManualExpensePayload, type ProfitAnalysis, type ProfitDailyItem } from "@/api/finance";
import { useAuthStore } from "@/stores/auth";
type ProfitViewState = "loading" | "error" | "empty" | "pending" | "ready";
type DataViewState = "loading" | "error" | "empty" | "ready";
type ExpenseCoverage = ProfitAnalysis["expense_coverage"][number];
const EXPENSE_LABELS: Record<ExpenseType, string> = { rent: "租金", wages: "工资", social_security: "社保", platform_fee: "平台费", utilities: "水电", logistics: "物流", marketing: "营销", other: "其他" };
const authStore = useAuthStore();
const canCreateExpense = computed(() => authStore.hasPermission("finance:expense:create"));
const canCreateCash = computed(() => authStore.hasPermission("finance:cash:create"));
const canViewCash = computed(() => authStore.hasPermission("finance:cash:view"));
const activeTab = ref("profit"); const submitting = ref(false);
const profitState = ref<ProfitViewState>("loading"); const profitError = ref(""); const profit = ref<ProfitAnalysis | null>(null);
const cashState = ref<DataViewState>("loading"); const cashError = ref(""); const cashSafety = ref<CashSafety | null>(null);
const dailyState = ref<DataViewState>("loading"); const dailyError = ref(""); const dailyItems = ref<ProfitDailyItem[]>([]);
const expenseForm = reactive<ManualExpensePayload>({ expense_date: "", store_code: "", expense_type: "rent", expense_amount: 0, data_type: "estimate", description: "" });
const cashForm = reactive<ManualCashPayload>({ record_date: "", account_type: "bank", account_name: "", balance: 0, data_type: "actual" });
const money = (value: number | null | undefined) => value == null ? "待接入" : "¥" + value.toLocaleString("zh-CN", { maximumFractionDigits: 2 });
const pct = (value: number | undefined) => value == null ? "待接入" : (value * 100).toFixed(1) + "%";
const expenseTypeLabel = (type: ExpenseType, label?: string) => label || EXPENSE_LABELS[type];
const expenseCoverageStatus = (item: ExpenseCoverage) => item.status === "ready" ? item.approved ? "已核准" : "已补录，待核准" : "待补录";
const dataTypeLabel = (type: FinanceDataType) => type === "actual" ? "财务核准" : "预估值（供参考）";
const dailyStatusLabel = (status: ProfitDailyItem["status"]) => status === "ready" ? "已就绪" : "待完整费用及核准";
const cashRiskLabel = (level: CashSafety["risk_level"]) => ({ critical: "危险", warning: "预警", normal: "安全", unknown: "待计算" })[level];
const cashRiskType = (level: CashSafety["risk_level"]) => level === "critical" ? "danger" : level === "warning" ? "warning" : "success";
const loadProfit = async () => { profitState.value = "loading"; profitError.value = ""; profit.value = null; try { const data = (await financeApi.getProfitAnalysis()).data.data; if (!data) { profitState.value = "empty"; return; } profit.value = data; profitState.value = data.status === "ready" ? "ready" : "pending"; } catch { profitError.value = "利润数据加载失败，请稍后重试"; profitState.value = "error"; } };
const loadCashSafety = async () => { cashState.value = "loading"; cashError.value = ""; cashSafety.value = null; try { const data = (await financeApi.getCashSafety()).data.data; if (!data) { cashState.value = "empty"; return; } cashSafety.value = data; cashState.value = "ready"; } catch { cashError.value = "现金安全数据加载失败，请稍后重试"; cashState.value = "error"; } };
const loadDaily = async () => { dailyState.value = "loading"; dailyError.value = ""; dailyItems.value = []; try { const items = (await financeApi.getProfitComparison()).data.data?.items || []; dailyItems.value = items; dailyState.value = items.length ? "ready" : "empty"; } catch { dailyError.value = "每日利润数据加载失败，请稍后重试"; dailyState.value = "error"; } };
const submitExpense = async () => { if (!expenseForm.expense_date || !expenseForm.expense_amount) return ElMessage.warning("请填写必填项"); submitting.value = true; try { await financeApi.createExpense(expenseForm); ElMessage.success("费用录入成功（" + dataTypeLabel(expenseForm.data_type) + "）"); } finally { submitting.value = false; } };
const submitCash = async () => { if (!cashForm.record_date || !cashForm.balance) return ElMessage.warning("请填写必填项"); submitting.value = true; try { await financeApi.createCash(cashForm); ElMessage.success("现金余额录入成功"); void loadCashSafety(); } finally { submitting.value = false; } };
onMounted(() => { void loadProfit(); if (canViewCash.value) void loadCashSafety(); void loadDaily(); });
</script>

<style scoped>
.page-container { padding: 0; }.page-header { margin-bottom: 16px; }.page-header h2 { font-size: 18px; color: #333; }.profit-analysis-page { background: #fff; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; }.profit-head { display: flex; justify-content: flex-end; align-items: center; gap: 10px; margin-bottom: 12px; }.profit-head > div { margin-right: auto; }.profit-head b { margin-right: 8px; }.period { font-size: 12px; color: #6b7280; }.state-panel { min-height: 160px; }.metric-grid, .cash-cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 10px; }.metric, .cash-card { border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px; background: #fff; display: flex; flex-direction: column; gap: 6px; }.metric span, .cash-card span { color: #6b7280; font-size: 12px; }.metric b, .cash-card b { color: #111827; font-size: 20px; }.expense-coverage-grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 8px; }.expense-coverage { display: flex; align-items: center; justify-content: space-between; gap: 8px; border: 1px solid #e5e7eb; border-radius: 6px; padding: 8px 10px; font-size: 12px; }.pending-line { margin: 10px 0; padding: 9px 12px; border-radius: 6px; background: #fff7ed; color: #9a5b13; }h3 { font-size: 14px; margin: 18px 0 10px; }.loss-grid { grid-template-columns: repeat(4, 1fr); }.cash-note { color: #6b7280; font-size: 12px; margin: 16px 0 0; }.refresh-button { margin-top: 12px; }
@media (max-width: 768px) { .profit-head { align-items: flex-start; flex-wrap: wrap; }.profit-head > div { width: 100%; margin-right: 0; }.profit-head .period { flex: 1 1 auto; }.loss-grid, .cash-cards { grid-template-columns: repeat(2, minmax(0, 1fr)); }.expense-coverage-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); } }
</style>
