"""add opening balance workflow controls

Revision ID: 016cfd3c1454
Revises: 1fdf4577d7d8
Create Date: 2026-07-29 23:30:01.262381

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '016cfd3c1454'
down_revision: Union[str, None] = '1fdf4577d7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
    CREATE TABLE fin_current.coverage_gap (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        book_id BIGINT NOT NULL REFERENCES fin_current.accounting_book(id),
        gap_start_date DATE NOT NULL, gap_end_date DATE NOT NULL,
        reason TEXT NOT NULL, affected_reports JSONB NOT NULL DEFAULT '[]'::jsonb,
        status VARCHAR(16) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','approved','discarded')),
        approved_by VARCHAR(128), approved_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT ck_fin_current_coverage_gap_dates CHECK (gap_end_date >= gap_start_date)
    );
    ALTER TABLE fin_current.opening_balance_batch
        ADD COLUMN coverage_gap_id BIGINT REFERENCES fin_current.coverage_gap(id),
        ADD COLUMN version INTEGER NOT NULL DEFAULT 1,
        ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
    ALTER TABLE fin_current.opening_balance_batch DROP CONSTRAINT uq_fin_current_opening_batch_scope;
    CREATE UNIQUE INDEX uq_fin_current_active_opening_batch_scope
        ON fin_current.opening_balance_batch(book_id, batch_kind, go_live_date)
        WHERE status <> 'discarded';
    CREATE TABLE fin_current.opening_balance_approval (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        batch_id BIGINT NOT NULL REFERENCES fin_current.opening_balance_batch(id),
        approval_step INTEGER NOT NULL DEFAULT 1, actor_id VARCHAR(128) NOT NULL,
        command_id VARCHAR(128) NOT NULL, reason TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT uq_fin_current_opening_approval_step UNIQUE (batch_id, approval_step),
        CONSTRAINT uq_fin_current_opening_approval_command UNIQUE (command_id)
    );
    CREATE TABLE fin_current.opening_balance_reconciliation_item (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        batch_id BIGINT NOT NULL REFERENCES fin_current.opening_balance_batch(id),
        account_version_id BIGINT NOT NULL REFERENCES fin_current.account_version(id),
        dimension_set_id BIGINT NOT NULL REFERENCES fin_current.dimension_set(id),
        currency_code VARCHAR(16) NOT NULL DEFAULT 'CNY',
        source_debit_amount NUMERIC(20,2) NOT NULL DEFAULT 0, source_credit_amount NUMERIC(20,2) NOT NULL DEFAULT 0,
        opening_debit_amount NUMERIC(20,2) NOT NULL DEFAULT 0, opening_credit_amount NUMERIC(20,2) NOT NULL DEFAULT 0,
        status VARCHAR(16) NOT NULL DEFAULT 'pending' CHECK (status IN ('matched','exception','pending')),
        exception_reason TEXT,
        CONSTRAINT uq_fin_current_opening_reconciliation_key UNIQUE (batch_id, account_version_id, dimension_set_id, currency_code)
    );
    CREATE OR REPLACE FUNCTION fin_current.guard_locked_opening_batch() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
        IF TG_OP = 'DELETE' AND OLD.status = 'locked' THEN
            RAISE EXCEPTION 'locked opening balance batch cannot be deleted';
        END IF;
        IF TG_OP = 'UPDATE' AND OLD.status = 'locked' AND NOT (
            NEW.status = 'discarded' AND OLD.batch_kind = 'final'
            AND NEW.book_id = OLD.book_id AND NEW.batch_kind = OLD.batch_kind
            AND NEW.history_coverage_end_date = OLD.history_coverage_end_date AND NEW.go_live_date = OLD.go_live_date
            AND NEW.coverage_continuous = OLD.coverage_continuous AND NEW.coverage_gap_id IS NOT DISTINCT FROM OLD.coverage_gap_id
            AND NEW.approved_by IS NOT DISTINCT FROM OLD.approved_by AND NEW.approved_at IS NOT DISTINCT FROM OLD.approved_at
            AND NEW.locked_at IS NOT DISTINCT FROM OLD.locked_at
            AND NOT EXISTS (SELECT 1 FROM fin_current.voucher WHERE book_id = OLD.book_id AND status = 'posted')
        ) THEN
            RAISE EXCEPTION 'locked opening balance batch can only be discarded before first posted voucher';
        END IF;
        IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
        RETURN NEW;
    END $$;
    CREATE TRIGGER trg_fin_current_guard_locked_opening_batch BEFORE UPDATE OR DELETE ON fin_current.opening_balance_batch
        FOR EACH ROW EXECUTE FUNCTION fin_current.guard_locked_opening_batch();
    CREATE OR REPLACE FUNCTION fin_current.guard_locked_opening_line() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE target_batch_id BIGINT;
    BEGIN
        target_batch_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.batch_id ELSE NEW.batch_id END;
        IF EXISTS (SELECT 1 FROM fin_current.opening_balance_batch b WHERE b.id = target_batch_id AND b.status = 'locked') THEN
            RAISE EXCEPTION 'locked opening balance lines cannot be modified';
        END IF;
        IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
        RETURN NEW;
    END $$;
    CREATE TRIGGER trg_fin_current_guard_locked_opening_line BEFORE INSERT OR UPDATE OR DELETE ON fin_current.opening_balance_line
        FOR EACH ROW EXECUTE FUNCTION fin_current.guard_locked_opening_line();
    """)


def downgrade() -> None:
    op.execute("""
    DROP TRIGGER IF EXISTS trg_fin_current_guard_locked_opening_line ON fin_current.opening_balance_line;
    DROP FUNCTION IF EXISTS fin_current.guard_locked_opening_line();
    DROP TRIGGER IF EXISTS trg_fin_current_guard_locked_opening_batch ON fin_current.opening_balance_batch;
    DROP FUNCTION IF EXISTS fin_current.guard_locked_opening_batch();
    DROP TABLE IF EXISTS fin_current.opening_balance_reconciliation_item;
    DROP TABLE IF EXISTS fin_current.opening_balance_approval;
    DROP INDEX IF EXISTS fin_current.uq_fin_current_active_opening_batch_scope;
    ALTER TABLE fin_current.opening_balance_batch ADD CONSTRAINT uq_fin_current_opening_batch_scope UNIQUE (book_id, batch_kind, go_live_date);
    ALTER TABLE fin_current.opening_balance_batch DROP COLUMN IF EXISTS updated_at, DROP COLUMN IF EXISTS version, DROP COLUMN IF EXISTS coverage_gap_id;
    DROP TABLE IF EXISTS fin_current.coverage_gap;
    """)
