"""add finance v2 period close workflow

Revision ID: 232ec287c52f
Revises: 354401508750
Create Date: 2026-07-29 15:14:35.320260

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '232ec287c52f'
down_revision: Union[str, None] = '354401508750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE fin_current.period_close_batch (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            book_id BIGINT NOT NULL REFERENCES fin_current.accounting_book(id),
            period_id BIGINT NOT NULL REFERENCES fin_current.fiscal_period(id),
            run_number INTEGER NOT NULL CHECK (run_number >= 1),
            close_kind VARCHAR(16) NOT NULL CHECK (close_kind IN ('month','year')),
            status VARCHAR(24) NOT NULL DEFAULT 'running'
                CHECK (status IN ('running','closed','failed','reopen_requested','reopened')),
            command_id VARCHAR(128) NOT NULL,
            check_report JSONB NOT NULL DEFAULT '{}'::jsonb,
            failure_reason TEXT,
            recovery_instructions TEXT,
            started_by VARCHAR(128) NOT NULL,
            closed_by VARCHAR(128),
            reopen_requested_by VARCHAR(128),
            reopen_reason TEXT,
            reopen_requested_at TIMESTAMPTZ,
            started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            closed_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_fin_current_period_close_run UNIQUE (period_id, run_number),
            CONSTRAINT uq_fin_current_period_close_command UNIQUE (command_id)
        );
        CREATE INDEX ix_fin_current_period_close_batch_period_status
            ON fin_current.period_close_batch (period_id, status, run_number DESC);
        CREATE TABLE fin_current.period_close_approval (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            batch_id BIGINT NOT NULL REFERENCES fin_current.period_close_batch(id),
            approval_step INTEGER NOT NULL CHECK (approval_step IN (1,2)),
            actor_id VARCHAR(128) NOT NULL,
            command_id VARCHAR(128) NOT NULL,
            reason TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_fin_current_period_close_approval_step UNIQUE (batch_id, approval_step),
            CONSTRAINT uq_fin_current_period_close_approval_actor UNIQUE (batch_id, actor_id),
            CONSTRAINT uq_fin_current_period_close_approval_command UNIQUE (command_id)
        );
        CREATE INDEX ix_fin_current_period_close_approval_batch
            ON fin_current.period_close_approval (batch_id, approval_step);
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS fin_current.period_close_approval")
    op.execute("DROP TABLE IF EXISTS fin_current.period_close_batch")
