"""Add the writable Huabang finance center.

Revision ID: 3e1f6a7b8c97
Revises: 2d1f6a7b8c96
"""

from alembic import op


revision = "3e1f6a7b8c97"
down_revision = "2d1f6a7b8c96"
branch_labels = None
depends_on = None


TABLE_NAMES = (
    "book",
    "period",
    "account",
    "aux_category",
    "aux_item",
    "voucher",
    "voucher_entry",
    "voucher_version",
    "ledger_balance",
    "statement_line",
    "statement_mapping",
    "operation_log",
    "source_link",
    "receivable",
    "payable",
    "settlement",
    "cash_account",
    "bank_transaction",
    "reconciliation",
    "fixed_asset",
    "depreciation",
    "invoice",
    "payroll",
    "tax_record",
    "auto_entry_rule",
    "auto_entry_run",
)

MIGRATION_MARKER = "migration:3e1f6a7b8c97"


DDL = r"""
CREATE TABLE fin."book" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legal_entity_id BIGINT NOT NULL REFERENCES dim.dim_legal_entity(id),
    book_code VARCHAR(64) NOT NULL,
    book_name VARCHAR(256) NOT NULL,
    short_name VARCHAR(128),
    base_currency VARCHAR(16) NOT NULL DEFAULT 'CNY',
    accounting_standard VARCHAR(32) NOT NULL DEFAULT 'small_enterprise',
    start_period VARCHAR(7) NOT NULL,
    current_period VARCHAR(7) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'active',
    version INTEGER NOT NULL DEFAULT 1,
    source_system VARCHAR(32) NOT NULL DEFAULT 'manual',
    source_database VARCHAR(128) NOT NULL DEFAULT '',
    source_pk VARCHAR(256),
    import_batch_id VARCHAR(64),
    source_updated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_book_legal_entity UNIQUE (legal_entity_id),
    CONSTRAINT uq_fin_book_code UNIQUE (book_code)
);

CREATE TABLE fin."period" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES fin."book"(id),
    period VARCHAR(7) NOT NULL,
    fiscal_year INTEGER NOT NULL,
    fiscal_period INTEGER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'open',
    closed_by BIGINT REFERENCES sys.sys_user(id),
    closed_at TIMESTAMPTZ,
    close_reason TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_period_book_period UNIQUE (book_id, period),
    CONSTRAINT uq_fin_period_book_id UNIQUE (book_id, id),
    CONSTRAINT ck_fin_period_status CHECK (status IN ('open', 'closed', 'locked'))
);
CREATE INDEX ix_fin_period_book_status ON fin."period" (book_id, status);

CREATE TABLE fin."account" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES fin."book"(id),
    account_code VARCHAR(64) NOT NULL,
    account_name VARCHAR(256) NOT NULL,
    parent_id BIGINT,
    account_level INTEGER NOT NULL DEFAULT 1,
    account_type VARCHAR(32) NOT NULL,
    balance_direction VARCHAR(8) NOT NULL,
    is_detail BOOLEAN NOT NULL DEFAULT true,
    is_cash BOOLEAN NOT NULL DEFAULT false,
    is_bank BOOLEAN NOT NULL DEFAULT false,
    has_quantity BOOLEAN NOT NULL DEFAULT false,
    has_foreign_currency BOOLEAN NOT NULL DEFAULT false,
    requires_auxiliary BOOLEAN NOT NULL DEFAULT false,
    is_active BOOLEAN NOT NULL DEFAULT true,
    version INTEGER NOT NULL DEFAULT 1,
    source_system VARCHAR(32) NOT NULL DEFAULT 'manual',
    source_database VARCHAR(128) NOT NULL DEFAULT '',
    source_pk VARCHAR(256),
    import_batch_id VARCHAR(64),
    source_updated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_account_book_code UNIQUE (book_id, account_code),
    CONSTRAINT uq_fin_account_book_id UNIQUE (book_id, id),
    CONSTRAINT fk_fin_account_book_parent FOREIGN KEY (book_id, parent_id)
        REFERENCES fin."account"(book_id, id),
    CONSTRAINT ck_fin_account_direction CHECK (balance_direction IN ('debit', 'credit'))
);
CREATE UNIQUE INDEX uq_fin_book_source ON fin."book"
    (source_system, source_database, source_pk) WHERE source_pk IS NOT NULL;
CREATE UNIQUE INDEX uq_fin_account_source ON fin."account"
    (book_id, source_system, source_database, source_pk) WHERE source_pk IS NOT NULL;
CREATE INDEX ix_fin_account_book_parent ON fin."account" (book_id, parent_id);

CREATE TABLE fin."aux_category" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES fin."book"(id),
    category_code VARCHAR(64) NOT NULL,
    category_name VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_aux_category_book_code UNIQUE (book_id, category_code),
    CONSTRAINT uq_fin_aux_category_book_id UNIQUE (book_id, id)
);

CREATE TABLE fin."aux_item" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES fin."book"(id),
    category_id BIGINT NOT NULL,
    item_code VARCHAR(128) NOT NULL,
    item_name VARCHAR(256) NOT NULL,
    target_type VARCHAR(32),
    target_code VARCHAR(128),
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    version INTEGER NOT NULL DEFAULT 1,
    source_system VARCHAR(32) NOT NULL DEFAULT 'manual',
    source_database VARCHAR(128) NOT NULL DEFAULT '',
    source_pk VARCHAR(256),
    import_batch_id VARCHAR(64),
    source_updated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_aux_item_book_category_code UNIQUE (book_id, category_id, item_code),
    CONSTRAINT uq_fin_aux_item_book_id UNIQUE (book_id, id),
    CONSTRAINT fk_fin_aux_item_book_category FOREIGN KEY (book_id, category_id)
        REFERENCES fin."aux_category"(book_id, id)
);
CREATE UNIQUE INDEX uq_fin_aux_item_source ON fin."aux_item"
    (book_id, source_system, source_database, source_pk) WHERE source_pk IS NOT NULL;

CREATE TABLE fin."voucher" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES fin."book"(id),
    period_id BIGINT NOT NULL,
    voucher_no VARCHAR(64) NOT NULL,
    voucher_group VARCHAR(32) NOT NULL DEFAULT '记',
    voucher_date DATE NOT NULL,
    period VARCHAR(7) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'draft',
    origin_kind VARCHAR(32) NOT NULL DEFAULT 'manual',
    source_status VARCHAR(32),
    summary VARCHAR(512),
    attachment_count INTEGER NOT NULL DEFAULT 0,
    total_debit NUMERIC(18,4) NOT NULL DEFAULT 0,
    total_credit NUMERIC(18,4) NOT NULL DEFAULT 0,
    prepared_by BIGINT REFERENCES sys.sys_user(id),
    prepared_name VARCHAR(128),
    reviewed_by BIGINT REFERENCES sys.sys_user(id),
    reviewed_at TIMESTAMPTZ,
    posted_by BIGINT REFERENCES sys.sys_user(id),
    posted_at TIMESTAMPTZ,
    reversal_of_id BIGINT,
    reversed_by_id BIGINT,
    version INTEGER NOT NULL DEFAULT 1,
    source_system VARCHAR(32) NOT NULL DEFAULT 'manual',
    source_database VARCHAR(128) NOT NULL DEFAULT '',
    source_pk VARCHAR(256),
    import_batch_id VARCHAR(64),
    source_updated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_voucher_book_no UNIQUE (book_id, voucher_no),
    CONSTRAINT uq_fin_voucher_book_id UNIQUE (book_id, id),
    CONSTRAINT fk_fin_voucher_book_period FOREIGN KEY (book_id, period_id)
        REFERENCES fin."period"(book_id, id),
    CONSTRAINT fk_fin_voucher_book_reversal_of FOREIGN KEY (book_id, reversal_of_id)
        REFERENCES fin."voucher"(book_id, id),
    CONSTRAINT fk_fin_voucher_book_reversed_by FOREIGN KEY (book_id, reversed_by_id)
        REFERENCES fin."voucher"(book_id, id),
    CONSTRAINT ck_fin_voucher_status CHECK (status IN ('draft', 'reviewed', 'posted', 'reversed')),
    CONSTRAINT ck_fin_voucher_nonnegative CHECK (total_debit >= 0 AND total_credit >= 0),
    CONSTRAINT ck_fin_voucher_balanced_state CHECK (status = 'draft' OR total_debit = total_credit)
);
CREATE UNIQUE INDEX uq_fin_voucher_source ON fin."voucher"
    (book_id, source_system, source_database, source_pk) WHERE source_pk IS NOT NULL;
CREATE INDEX ix_fin_voucher_book_period_status ON fin."voucher" (book_id, period, status);
CREATE INDEX ix_fin_voucher_book_period_id ON fin."voucher" (book_id, period_id);
CREATE INDEX ix_fin_voucher_reversal_of ON fin."voucher" (reversal_of_id);
CREATE INDEX ix_fin_voucher_reversed_by ON fin."voucher" (reversed_by_id);

CREATE TABLE fin."voucher_entry" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES fin."book"(id),
    voucher_id BIGINT NOT NULL,
    line_no INTEGER NOT NULL,
    account_id BIGINT NOT NULL,
    summary VARCHAR(512) NOT NULL,
    debit_amount NUMERIC(18,4) NOT NULL DEFAULT 0,
    credit_amount NUMERIC(18,4) NOT NULL DEFAULT 0,
    currency_code VARCHAR(16) NOT NULL DEFAULT 'CNY',
    exchange_rate NUMERIC(18,8) NOT NULL DEFAULT 1,
    original_amount NUMERIC(18,4),
    quantity NUMERIC(18,6),
    unit_price NUMERIC(18,6),
    aux_items JSONB NOT NULL DEFAULT '{}'::jsonb,
    cash_flow_item VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_voucher_entry_line UNIQUE (voucher_id, line_no),
    CONSTRAINT fk_fin_voucher_entry_book_voucher FOREIGN KEY (book_id, voucher_id)
        REFERENCES fin."voucher"(book_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_fin_voucher_entry_book_account FOREIGN KEY (book_id, account_id)
        REFERENCES fin."account"(book_id, id),
    CONSTRAINT ck_fin_voucher_entry_side CHECK (
        (debit_amount > 0 AND credit_amount = 0) OR
        (credit_amount > 0 AND debit_amount = 0)
    )
);
CREATE INDEX ix_fin_voucher_entry_account ON fin."voucher_entry" (book_id, account_id);
CREATE INDEX ix_fin_voucher_entry_book_voucher ON fin."voucher_entry" (book_id, voucher_id);

CREATE TABLE fin."voucher_version" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES fin."book"(id),
    voucher_id BIGINT NOT NULL,
    version INTEGER NOT NULL,
    action VARCHAR(32) NOT NULL,
    before_snapshot JSONB,
    after_snapshot JSONB,
    actor_id BIGINT REFERENCES sys.sys_user(id),
    actor_name VARCHAR(128),
    reason TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_voucher_version UNIQUE (voucher_id, version),
    CONSTRAINT fk_fin_voucher_version_book_voucher FOREIGN KEY (book_id, voucher_id)
        REFERENCES fin."voucher"(book_id, id) ON DELETE CASCADE
);
CREATE INDEX ix_fin_voucher_version_book_voucher ON fin."voucher_version" (book_id, voucher_id);

CREATE TABLE fin."ledger_balance" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES fin."book"(id),
    account_id BIGINT NOT NULL,
    period_id BIGINT NOT NULL,
    period VARCHAR(7) NOT NULL,
    balance_direction VARCHAR(8) NOT NULL,
    opening_amount NUMERIC(18,4) NOT NULL DEFAULT 0,
    period_debit NUMERIC(18,4) NOT NULL DEFAULT 0,
    period_credit NUMERIC(18,4) NOT NULL DEFAULT 0,
    closing_amount NUMERIC(18,4) NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_ledger_balance_scope UNIQUE (book_id, account_id, period),
    CONSTRAINT fk_fin_ledger_balance_book_account FOREIGN KEY (book_id, account_id)
        REFERENCES fin."account"(book_id, id),
    CONSTRAINT fk_fin_ledger_balance_book_period FOREIGN KEY (book_id, period_id)
        REFERENCES fin."period"(book_id, id),
    CONSTRAINT ck_fin_ledger_direction CHECK (balance_direction IN ('debit', 'credit')),
    CONSTRAINT ck_fin_ledger_nonnegative CHECK (
        opening_amount >= 0 AND period_debit >= 0 AND period_credit >= 0 AND closing_amount >= 0
    ),
    CONSTRAINT ck_fin_ledger_equation CHECK (
        (balance_direction = 'debit' AND closing_amount = opening_amount + period_debit - period_credit) OR
        (balance_direction = 'credit' AND closing_amount = opening_amount + period_credit - period_debit)
    )
);
CREATE INDEX ix_fin_ledger_balance_book_period ON fin."ledger_balance" (book_id, period_id);

CREATE TABLE fin."statement_line" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_code VARCHAR(64) NOT NULL,
    template_version INTEGER NOT NULL DEFAULT 1,
    statement_type VARCHAR(32) NOT NULL,
    line_code VARCHAR(64) NOT NULL,
    line_name VARCHAR(128) NOT NULL,
    parent_line_id BIGINT REFERENCES fin."statement_line"(id),
    display_order INTEGER NOT NULL DEFAULT 0,
    formula_kind VARCHAR(24) NOT NULL DEFAULT 'mapping',
    formula JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_statement_line_template UNIQUE
        (template_code, template_version, statement_type, line_code)
);

CREATE TABLE fin."statement_mapping" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES fin."book"(id),
    account_id BIGINT NOT NULL,
    statement_line_id BIGINT NOT NULL REFERENCES fin."statement_line"(id),
    statement_type VARCHAR(32) NOT NULL,
    amount_sign INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(24) NOT NULL DEFAULT 'suggested',
    mapping_source VARCHAR(24) NOT NULL DEFAULT 'account_code',
    confirmed_by BIGINT REFERENCES sys.sys_user(id),
    confirmed_at TIMESTAMPTZ,
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_statement_mapping UNIQUE (book_id, account_id, statement_line_id),
    CONSTRAINT fk_fin_statement_mapping_book_account FOREIGN KEY (book_id, account_id)
        REFERENCES fin."account"(book_id, id)
);
CREATE INDEX ix_fin_statement_mapping_book_account ON fin."statement_mapping" (book_id, account_id);

CREATE TABLE fin."operation_log" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES fin."book"(id),
    actor_id BIGINT REFERENCES sys.sys_user(id),
    actor_name VARCHAR(128),
    action VARCHAR(64) NOT NULL,
    target_type VARCHAR(64) NOT NULL,
    target_id VARCHAR(128) NOT NULL,
    reason TEXT NOT NULL,
    before_data JSONB,
    after_data JSONB,
    request_id VARCHAR(64),
    client_ip VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_fin_operation_log_target ON fin."operation_log" (book_id, target_type, target_id);

CREATE TABLE fin."source_link" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES fin."book"(id),
    target_type VARCHAR(64) NOT NULL,
    target_id BIGINT NOT NULL,
    source_system VARCHAR(32) NOT NULL,
    source_database VARCHAR(128) NOT NULL DEFAULT '',
    source_pk VARCHAR(256) NOT NULL,
    import_batch_id VARCHAR(64) NOT NULL DEFAULT 'manual',
    source_updated_at TIMESTAMPTZ,
    source_hash VARCHAR(64),
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_source_link_source UNIQUE (book_id, source_system, source_database, source_pk)
);
CREATE INDEX ix_fin_source_link_target ON fin."source_link" (book_id, target_type, target_id);

CREATE TABLE fin."receivable" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES fin."book"(id),
    draft_voucher_id BIGINT,
    document_no VARCHAR(128) NOT NULL,
    counterparty_aux_id BIGINT NOT NULL,
    business_date DATE NOT NULL,
    due_date DATE,
    currency_code VARCHAR(16) NOT NULL DEFAULT 'CNY',
    original_amount NUMERIC(18,4) NOT NULL,
    settled_amount NUMERIC(18,4) NOT NULL DEFAULT 0,
    outstanding_amount NUMERIC(18,4) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'open',
    version INTEGER NOT NULL DEFAULT 1,
    source_system VARCHAR(32) NOT NULL DEFAULT 'manual',
    source_database VARCHAR(128) NOT NULL DEFAULT '',
    source_pk VARCHAR(256),
    import_batch_id VARCHAR(64),
    source_updated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_receivable_book_id UNIQUE (book_id, id),
    CONSTRAINT fk_fin_receivable_book_voucher FOREIGN KEY (book_id, draft_voucher_id)
        REFERENCES fin."voucher"(book_id, id),
    CONSTRAINT fk_fin_receivable_book_counterparty FOREIGN KEY (book_id, counterparty_aux_id)
        REFERENCES fin."aux_item"(book_id, id),
    CONSTRAINT ck_fin_receivable_amounts CHECK (
        original_amount >= 0 AND settled_amount >= 0 AND settled_amount <= original_amount AND
        outstanding_amount = original_amount - settled_amount
    )
);
CREATE INDEX ix_fin_receivable_book_status_due ON fin."receivable" (book_id, status, due_date);
CREATE INDEX ix_fin_receivable_book_voucher ON fin."receivable" (book_id, draft_voucher_id);
CREATE INDEX ix_fin_receivable_book_counterparty ON fin."receivable" (book_id, counterparty_aux_id);
CREATE UNIQUE INDEX uq_fin_receivable_source ON fin."receivable"
    (book_id, source_system, source_database, source_pk) WHERE source_pk IS NOT NULL;

CREATE TABLE fin."payable" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES fin."book"(id),
    draft_voucher_id BIGINT,
    document_no VARCHAR(128) NOT NULL,
    counterparty_aux_id BIGINT NOT NULL,
    business_date DATE NOT NULL,
    due_date DATE,
    currency_code VARCHAR(16) NOT NULL DEFAULT 'CNY',
    original_amount NUMERIC(18,4) NOT NULL,
    settled_amount NUMERIC(18,4) NOT NULL DEFAULT 0,
    outstanding_amount NUMERIC(18,4) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'open',
    version INTEGER NOT NULL DEFAULT 1,
    source_system VARCHAR(32) NOT NULL DEFAULT 'manual',
    source_database VARCHAR(128) NOT NULL DEFAULT '',
    source_pk VARCHAR(256),
    import_batch_id VARCHAR(64),
    source_updated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_payable_book_id UNIQUE (book_id, id),
    CONSTRAINT fk_fin_payable_book_voucher FOREIGN KEY (book_id, draft_voucher_id)
        REFERENCES fin."voucher"(book_id, id),
    CONSTRAINT fk_fin_payable_book_counterparty FOREIGN KEY (book_id, counterparty_aux_id)
        REFERENCES fin."aux_item"(book_id, id),
    CONSTRAINT ck_fin_payable_amounts CHECK (
        original_amount >= 0 AND settled_amount >= 0 AND settled_amount <= original_amount AND
        outstanding_amount = original_amount - settled_amount
    )
);
CREATE INDEX ix_fin_payable_book_status_due ON fin."payable" (book_id, status, due_date);
CREATE INDEX ix_fin_payable_book_voucher ON fin."payable" (book_id, draft_voucher_id);
CREATE INDEX ix_fin_payable_book_counterparty ON fin."payable" (book_id, counterparty_aux_id);
CREATE UNIQUE INDEX uq_fin_payable_source ON fin."payable"
    (book_id, source_system, source_database, source_pk) WHERE source_pk IS NOT NULL;

CREATE TABLE fin."settlement" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES fin."book"(id),
    draft_voucher_id BIGINT,
    settlement_no VARCHAR(128) NOT NULL,
    settlement_type VARCHAR(16) NOT NULL,
    receivable_id BIGINT,
    payable_id BIGINT,
    settlement_date DATE NOT NULL,
    amount NUMERIC(18,4) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    reversal_of_id BIGINT,
    actor_id BIGINT REFERENCES sys.sys_user(id),
    reason TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_settlement_book_no UNIQUE (book_id, settlement_no),
    CONSTRAINT uq_fin_settlement_book_id UNIQUE (book_id, id),
    CONSTRAINT fk_fin_settlement_book_voucher FOREIGN KEY (book_id, draft_voucher_id)
        REFERENCES fin."voucher"(book_id, id),
    CONSTRAINT fk_fin_settlement_book_reversal FOREIGN KEY (book_id, reversal_of_id)
        REFERENCES fin."settlement"(book_id, id),
    CONSTRAINT fk_fin_settlement_book_receivable FOREIGN KEY (book_id, receivable_id)
        REFERENCES fin."receivable"(book_id, id),
    CONSTRAINT fk_fin_settlement_book_payable FOREIGN KEY (book_id, payable_id)
        REFERENCES fin."payable"(book_id, id),
    CONSTRAINT ck_fin_settlement_amount CHECK (amount > 0),
    CONSTRAINT ck_fin_settlement_one_target CHECK (
        (receivable_id IS NOT NULL)::integer + (payable_id IS NOT NULL)::integer = 1
    )
);
CREATE INDEX ix_fin_settlement_book_voucher ON fin."settlement" (book_id, draft_voucher_id);
CREATE INDEX ix_fin_settlement_book_reversal ON fin."settlement" (book_id, reversal_of_id);
CREATE INDEX ix_fin_settlement_book_receivable ON fin."settlement" (book_id, receivable_id);
CREATE INDEX ix_fin_settlement_book_payable ON fin."settlement" (book_id, payable_id);

CREATE TABLE fin."cash_account" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES fin."book"(id),
    account_code VARCHAR(64) NOT NULL,
    account_name VARCHAR(128) NOT NULL,
    account_type VARCHAR(16) NOT NULL,
    ledger_account_id BIGINT NOT NULL,
    bank_name VARCHAR(128),
    bank_account_masked VARCHAR(64),
    currency_code VARCHAR(16) NOT NULL DEFAULT 'CNY',
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_cash_account_book_code UNIQUE (book_id, account_code),
    CONSTRAINT uq_fin_cash_account_book_id UNIQUE (book_id, id),
    CONSTRAINT fk_fin_cash_account_book_account FOREIGN KEY (book_id, ledger_account_id)
        REFERENCES fin."account"(book_id, id)
);
CREATE INDEX ix_fin_cash_account_book_account ON fin."cash_account" (book_id, ledger_account_id);

CREATE TABLE fin."bank_transaction" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES fin."book"(id),
    draft_voucher_id BIGINT,
    cash_account_id BIGINT NOT NULL,
    transaction_date DATE NOT NULL,
    amount NUMERIC(18,4) NOT NULL,
    direction VARCHAR(8) NOT NULL,
    counterparty_name VARCHAR(256),
    reference_no VARCHAR(128),
    summary VARCHAR(512),
    statement_hash VARCHAR(64) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'unreconciled',
    version INTEGER NOT NULL DEFAULT 1,
    source_system VARCHAR(32) NOT NULL DEFAULT 'manual',
    source_database VARCHAR(128) NOT NULL DEFAULT '',
    source_pk VARCHAR(256),
    import_batch_id VARCHAR(64),
    source_updated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_bank_transaction_hash UNIQUE (cash_account_id, statement_hash),
    CONSTRAINT fk_fin_bank_transaction_book_voucher FOREIGN KEY (book_id, draft_voucher_id)
        REFERENCES fin."voucher"(book_id, id),
    CONSTRAINT fk_fin_bank_transaction_book_cash FOREIGN KEY (book_id, cash_account_id)
        REFERENCES fin."cash_account"(book_id, id),
    CONSTRAINT ck_fin_bank_transaction_amount_direction CHECK (amount > 0 AND direction IN ('in','out'))
);
CREATE INDEX ix_fin_bank_transaction_book_voucher ON fin."bank_transaction" (book_id, draft_voucher_id);
CREATE INDEX ix_fin_bank_transaction_book_cash ON fin."bank_transaction" (book_id, cash_account_id);
CREATE UNIQUE INDEX uq_fin_bank_transaction_source ON fin."bank_transaction"
    (book_id, source_system, source_database, source_pk) WHERE source_pk IS NOT NULL;

CREATE TABLE fin."reconciliation" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES fin."book"(id),
    draft_voucher_id BIGINT,
    reconciliation_no VARCHAR(128) NOT NULL,
    cash_account_id BIGINT NOT NULL,
    period VARCHAR(7) NOT NULL,
    statement_balance NUMERIC(18,4) NOT NULL,
    ledger_balance NUMERIC(18,4) NOT NULL,
    difference NUMERIC(18,4) NOT NULL,
    matched_transaction_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    status VARCHAR(16) NOT NULL DEFAULT 'draft',
    reviewed_by BIGINT REFERENCES sys.sys_user(id),
    reviewed_at TIMESTAMPTZ,
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_reconciliation_book_no UNIQUE (book_id, reconciliation_no),
    CONSTRAINT fk_fin_reconciliation_book_voucher FOREIGN KEY (book_id, draft_voucher_id)
        REFERENCES fin."voucher"(book_id, id),
    CONSTRAINT fk_fin_reconciliation_book_cash FOREIGN KEY (book_id, cash_account_id)
        REFERENCES fin."cash_account"(book_id, id),
    CONSTRAINT ck_fin_reconciliation_difference CHECK (difference = statement_balance - ledger_balance)
);
CREATE INDEX ix_fin_reconciliation_book_voucher ON fin."reconciliation" (book_id, draft_voucher_id);
CREATE INDEX ix_fin_reconciliation_book_cash ON fin."reconciliation" (book_id, cash_account_id);

CREATE TABLE fin."fixed_asset" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES fin."book"(id),
    draft_voucher_id BIGINT,
    asset_code VARCHAR(64) NOT NULL,
    asset_name VARCHAR(256) NOT NULL,
    category VARCHAR(64) NOT NULL,
    acquisition_date DATE NOT NULL,
    in_service_date DATE NOT NULL,
    original_cost NUMERIC(18,4) NOT NULL,
    residual_rate NUMERIC(8,6) NOT NULL DEFAULT 0,
    useful_life_months INTEGER NOT NULL,
    accumulated_depreciation NUMERIC(18,4) NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    department_aux_id BIGINT,
    expense_account_id BIGINT NOT NULL,
    accumulated_account_id BIGINT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_fixed_asset_book_code UNIQUE (book_id, asset_code),
    CONSTRAINT uq_fin_fixed_asset_book_id UNIQUE (book_id, id),
    CONSTRAINT fk_fin_fixed_asset_book_voucher FOREIGN KEY (book_id, draft_voucher_id)
        REFERENCES fin."voucher"(book_id, id),
    CONSTRAINT fk_fin_fixed_asset_book_department FOREIGN KEY (book_id, department_aux_id)
        REFERENCES fin."aux_item"(book_id, id),
    CONSTRAINT fk_fin_fixed_asset_book_expense FOREIGN KEY (book_id, expense_account_id)
        REFERENCES fin."account"(book_id, id),
    CONSTRAINT fk_fin_fixed_asset_book_accumulated FOREIGN KEY (book_id, accumulated_account_id)
        REFERENCES fin."account"(book_id, id),
    CONSTRAINT ck_fin_fixed_asset_amounts CHECK (
        original_cost > 0 AND useful_life_months > 0 AND residual_rate >= 0 AND residual_rate < 1 AND
        accumulated_depreciation >= 0 AND accumulated_depreciation <= original_cost
    )
);
CREATE INDEX ix_fin_fixed_asset_book_voucher ON fin."fixed_asset" (book_id, draft_voucher_id);
CREATE INDEX ix_fin_fixed_asset_book_department ON fin."fixed_asset" (book_id, department_aux_id);
CREATE INDEX ix_fin_fixed_asset_book_expense ON fin."fixed_asset" (book_id, expense_account_id);
CREATE INDEX ix_fin_fixed_asset_book_accumulated ON fin."fixed_asset" (book_id, accumulated_account_id);

CREATE TABLE fin."depreciation" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES fin."book"(id),
    draft_voucher_id BIGINT,
    fixed_asset_id BIGINT NOT NULL,
    period VARCHAR(7) NOT NULL,
    depreciation_date DATE NOT NULL,
    amount NUMERIC(18,4) NOT NULL,
    accumulated_amount NUMERIC(18,4) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'scheduled',
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_depreciation_asset_period UNIQUE (fixed_asset_id, period),
    CONSTRAINT fk_fin_depreciation_book_voucher FOREIGN KEY (book_id, draft_voucher_id)
        REFERENCES fin."voucher"(book_id, id),
    CONSTRAINT fk_fin_depreciation_book_asset FOREIGN KEY (book_id, fixed_asset_id)
        REFERENCES fin."fixed_asset"(book_id, id),
    CONSTRAINT ck_fin_depreciation_amounts CHECK (amount >= 0 AND accumulated_amount >= amount)
);
CREATE INDEX ix_fin_depreciation_book_voucher ON fin."depreciation" (book_id, draft_voucher_id);
CREATE INDEX ix_fin_depreciation_book_asset ON fin."depreciation" (book_id, fixed_asset_id);

CREATE TABLE fin."invoice" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES fin."book"(id),
    draft_voucher_id BIGINT,
    invoice_code VARCHAR(64) NOT NULL DEFAULT '',
    invoice_no VARCHAR(128) NOT NULL,
    invoice_type VARCHAR(32) NOT NULL,
    direction VARCHAR(8) NOT NULL,
    invoice_date DATE NOT NULL,
    counterparty_aux_id BIGINT,
    amount_excluding_tax NUMERIC(18,4) NOT NULL,
    tax_amount NUMERIC(18,4) NOT NULL,
    total_amount NUMERIC(18,4) NOT NULL,
    currency_code VARCHAR(16) NOT NULL DEFAULT 'CNY',
    status VARCHAR(16) NOT NULL DEFAULT 'registered',
    version INTEGER NOT NULL DEFAULT 1,
    source_system VARCHAR(32) NOT NULL DEFAULT 'manual',
    source_database VARCHAR(128) NOT NULL DEFAULT '',
    source_pk VARCHAR(256),
    import_batch_id VARCHAR(64),
    source_updated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_invoice_identity UNIQUE (book_id, invoice_code, invoice_no),
    CONSTRAINT fk_fin_invoice_book_voucher FOREIGN KEY (book_id, draft_voucher_id)
        REFERENCES fin."voucher"(book_id, id),
    CONSTRAINT fk_fin_invoice_book_counterparty FOREIGN KEY (book_id, counterparty_aux_id)
        REFERENCES fin."aux_item"(book_id, id),
    CONSTRAINT ck_fin_invoice_total CHECK (
        amount_excluding_tax >= 0 AND tax_amount >= 0 AND amount_excluding_tax + tax_amount = total_amount
    )
);
CREATE INDEX ix_fin_invoice_book_voucher ON fin."invoice" (book_id, draft_voucher_id);
CREATE INDEX ix_fin_invoice_book_counterparty ON fin."invoice" (book_id, counterparty_aux_id);
CREATE UNIQUE INDEX uq_fin_invoice_source ON fin."invoice"
    (book_id, source_system, source_database, source_pk) WHERE source_pk IS NOT NULL;

CREATE TABLE fin."payroll" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES fin."book"(id),
    draft_voucher_id BIGINT,
    period VARCHAR(7) NOT NULL,
    employee_aux_id BIGINT NOT NULL,
    department_aux_id BIGINT,
    gross_amount NUMERIC(18,4) NOT NULL,
    social_security_amount NUMERIC(18,4) NOT NULL DEFAULT 0,
    housing_fund_amount NUMERIC(18,4) NOT NULL DEFAULT 0,
    tax_amount NUMERIC(18,4) NOT NULL DEFAULT 0,
    other_deduction NUMERIC(18,4) NOT NULL DEFAULT 0,
    net_amount NUMERIC(18,4) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'draft',
    version INTEGER NOT NULL DEFAULT 1,
    source_system VARCHAR(32) NOT NULL DEFAULT 'manual',
    source_database VARCHAR(128) NOT NULL DEFAULT '',
    source_pk VARCHAR(256),
    import_batch_id VARCHAR(64),
    source_updated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_payroll_employee_period UNIQUE (book_id, period, employee_aux_id),
    CONSTRAINT fk_fin_payroll_book_voucher FOREIGN KEY (book_id, draft_voucher_id)
        REFERENCES fin."voucher"(book_id, id),
    CONSTRAINT fk_fin_payroll_book_employee FOREIGN KEY (book_id, employee_aux_id)
        REFERENCES fin."aux_item"(book_id, id),
    CONSTRAINT fk_fin_payroll_book_department FOREIGN KEY (book_id, department_aux_id)
        REFERENCES fin."aux_item"(book_id, id),
    CONSTRAINT ck_fin_payroll_total CHECK (
        gross_amount >= 0 AND social_security_amount >= 0 AND housing_fund_amount >= 0 AND
        tax_amount >= 0 AND other_deduction >= 0 AND
        net_amount = gross_amount - social_security_amount - housing_fund_amount - tax_amount - other_deduction
    )
);
CREATE INDEX ix_fin_payroll_book_voucher ON fin."payroll" (book_id, draft_voucher_id);
CREATE INDEX ix_fin_payroll_book_employee ON fin."payroll" (book_id, employee_aux_id);
CREATE INDEX ix_fin_payroll_book_department ON fin."payroll" (book_id, department_aux_id);
CREATE UNIQUE INDEX uq_fin_payroll_source ON fin."payroll"
    (book_id, source_system, source_database, source_pk) WHERE source_pk IS NOT NULL;

CREATE TABLE fin."tax_record" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES fin."book"(id),
    draft_voucher_id BIGINT,
    tax_type VARCHAR(64) NOT NULL,
    period VARCHAR(7) NOT NULL,
    taxable_amount NUMERIC(18,4) NOT NULL DEFAULT 0,
    tax_amount NUMERIC(18,4) NOT NULL,
    paid_amount NUMERIC(18,4) NOT NULL DEFAULT 0,
    due_date DATE,
    paid_date DATE,
    status VARCHAR(16) NOT NULL DEFAULT 'unpaid',
    version INTEGER NOT NULL DEFAULT 1,
    source_system VARCHAR(32) NOT NULL DEFAULT 'manual',
    source_database VARCHAR(128) NOT NULL DEFAULT '',
    source_pk VARCHAR(256),
    import_batch_id VARCHAR(64),
    source_updated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_tax_record_scope UNIQUE (book_id, tax_type, period),
    CONSTRAINT fk_fin_tax_record_book_voucher FOREIGN KEY (book_id, draft_voucher_id)
        REFERENCES fin."voucher"(book_id, id),
    CONSTRAINT ck_fin_tax_record_amounts CHECK (
        taxable_amount >= 0 AND tax_amount >= 0 AND paid_amount >= 0 AND paid_amount <= tax_amount
    )
);
CREATE INDEX ix_fin_tax_record_book_voucher ON fin."tax_record" (book_id, draft_voucher_id);
CREATE UNIQUE INDEX uq_fin_tax_record_source ON fin."tax_record"
    (book_id, source_system, source_database, source_pk) WHERE source_pk IS NOT NULL;

CREATE TABLE fin."auto_entry_rule" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES fin."book"(id),
    rule_name VARCHAR(128) NOT NULL,
    business_type VARCHAR(64) NOT NULL,
    source_system VARCHAR(32) NOT NULL,
    effective_from VARCHAR(7) NOT NULL,
    effective_to VARCHAR(7),
    priority INTEGER NOT NULL DEFAULT 100,
    conditions JSONB NOT NULL DEFAULT '{}'::jsonb,
    entry_template JSONB NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_auto_entry_rule_scope UNIQUE (book_id, business_type, effective_from, priority)
);

CREATE TABLE fin."auto_entry_run" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES fin."book"(id),
    draft_voucher_id BIGINT,
    run_key VARCHAR(128) NOT NULL,
    source_system VARCHAR(32) NOT NULL,
    business_type VARCHAR(64) NOT NULL,
    mode VARCHAR(16) NOT NULL DEFAULT 'preview',
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    source_count INTEGER NOT NULL DEFAULT 0,
    draft_count INTEGER NOT NULL DEFAULT 0,
    exception_count INTEGER NOT NULL DEFAULT 0,
    input_hash VARCHAR(64) NOT NULL,
    result JSONB NOT NULL DEFAULT '{}'::jsonb,
    error_message TEXT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_fin_auto_entry_run_key UNIQUE (book_id, run_key),
    CONSTRAINT fk_fin_auto_entry_run_book_voucher FOREIGN KEY (book_id, draft_voucher_id)
        REFERENCES fin."voucher"(book_id, id)
);
CREATE INDEX ix_fin_auto_entry_run_book_voucher ON fin."auto_entry_run" (book_id, draft_voucher_id);
"""


VOUCHER_GUARD_DDL = r"""
CREATE OR REPLACE FUNCTION fin.validate_voucher_integrity()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    entry_count integer;
    entry_debit numeric(18,4);
    entry_credit numeric(18,4);
    period_state varchar(16);
BEGIN
    IF NEW.status <> 'draft' THEN
        SELECT COUNT(*), COALESCE(SUM(debit_amount), 0), COALESCE(SUM(credit_amount), 0)
        INTO entry_count, entry_debit, entry_credit
        FROM fin."voucher_entry"
        WHERE book_id = NEW.book_id AND voucher_id = NEW.id;

        IF entry_count = 0 THEN
            RAISE EXCEPTION 'Voucher % in book % cannot be % without entries', NEW.id, NEW.book_id, NEW.status;
        END IF;
        IF NEW.total_debit <> NEW.total_credit THEN
            RAISE EXCEPTION 'Voucher % in book % is not balanced: debit %, credit %',
                NEW.id, NEW.book_id, NEW.total_debit, NEW.total_credit;
        END IF;
        IF NEW.total_debit <> entry_debit OR NEW.total_credit <> entry_credit THEN
            RAISE EXCEPTION 'Voucher % in book % header totals do not match entry totals: header %, %, entries %, %',
                NEW.id, NEW.book_id, NEW.total_debit, NEW.total_credit, entry_debit, entry_credit;
        END IF;

        SELECT status INTO period_state
        FROM fin."period"
        WHERE book_id = NEW.book_id AND id = NEW.period_id;

        IF period_state IS NULL THEN
            RAISE EXCEPTION 'Voucher % in book % references missing period %', NEW.id, NEW.book_id, NEW.period_id;
        END IF;
        IF NEW.origin_kind <> 'kingdee_history' AND period_state <> 'open' THEN
            RAISE EXCEPTION 'Voucher % in book % cannot be % in % period %',
                NEW.id, NEW.book_id, NEW.status, period_state, NEW.period;
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE CONSTRAINT TRIGGER fin_validate_voucher
AFTER INSERT OR UPDATE ON fin."voucher"
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION fin.validate_voucher_integrity();

CREATE OR REPLACE FUNCTION fin.guard_voucher_entry_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    voucher_state varchar(16);
    checked_book_id bigint;
    checked_voucher_id bigint;
BEGIN
    checked_book_id := OLD.book_id;
    checked_voucher_id := OLD.voucher_id;

    IF checked_voucher_id IS NOT NULL THEN
        SELECT status INTO voucher_state
        FROM fin."voucher"
        WHERE book_id = checked_book_id AND id = checked_voucher_id;

        IF voucher_state IS NOT NULL AND voucher_state <> 'draft' THEN
            RAISE EXCEPTION 'Voucher % in book % is %, entries are immutable',
                checked_voucher_id, checked_book_id, voucher_state;
        END IF;
    END IF;

    checked_book_id := NEW.book_id;
    checked_voucher_id := NEW.voucher_id;

    IF checked_voucher_id IS NOT NULL THEN
        SELECT status INTO voucher_state
        FROM fin."voucher"
        WHERE book_id = checked_book_id AND id = checked_voucher_id;

        IF voucher_state IS NOT NULL AND voucher_state <> 'draft' THEN
            RAISE EXCEPTION 'Voucher % in book % is %, entries are immutable',
                checked_voucher_id, checked_book_id, voucher_state;
        END IF;
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE TRIGGER fin_guard_voucher_entry_mutation
BEFORE INSERT OR UPDATE OR DELETE ON fin."voucher_entry"
FOR EACH ROW EXECUTE FUNCTION fin.guard_voucher_entry_mutation();

CREATE OR REPLACE FUNCTION fin.guard_draft_voucher_reference()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    voucher_state varchar(16);
BEGIN
    IF NEW.draft_voucher_id IS NOT NULL THEN
        SELECT status INTO voucher_state
        FROM fin."voucher"
        WHERE book_id = NEW.book_id AND id = NEW.draft_voucher_id;

        IF voucher_state IS NULL THEN
            RAISE EXCEPTION 'Draft voucher % in book % is missing', NEW.draft_voucher_id, NEW.book_id;
        END IF;
        IF voucher_state <> 'draft' THEN
            RAISE EXCEPTION 'Voucher % in book % is %, operation records require draft vouchers',
                NEW.draft_voucher_id, NEW.book_id, voucher_state;
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER fin_guard_receivable_draft_voucher
BEFORE INSERT OR UPDATE OF book_id, draft_voucher_id ON fin."receivable"
FOR EACH ROW EXECUTE FUNCTION fin.guard_draft_voucher_reference();
CREATE TRIGGER fin_guard_payable_draft_voucher
BEFORE INSERT OR UPDATE OF book_id, draft_voucher_id ON fin."payable"
FOR EACH ROW EXECUTE FUNCTION fin.guard_draft_voucher_reference();
CREATE TRIGGER fin_guard_settlement_draft_voucher
BEFORE INSERT OR UPDATE OF book_id, draft_voucher_id ON fin."settlement"
FOR EACH ROW EXECUTE FUNCTION fin.guard_draft_voucher_reference();
CREATE TRIGGER fin_guard_bank_transaction_draft_voucher
BEFORE INSERT OR UPDATE OF book_id, draft_voucher_id ON fin."bank_transaction"
FOR EACH ROW EXECUTE FUNCTION fin.guard_draft_voucher_reference();
CREATE TRIGGER fin_guard_reconciliation_draft_voucher
BEFORE INSERT OR UPDATE OF book_id, draft_voucher_id ON fin."reconciliation"
FOR EACH ROW EXECUTE FUNCTION fin.guard_draft_voucher_reference();
CREATE TRIGGER fin_guard_fixed_asset_draft_voucher
BEFORE INSERT OR UPDATE OF book_id, draft_voucher_id ON fin."fixed_asset"
FOR EACH ROW EXECUTE FUNCTION fin.guard_draft_voucher_reference();
CREATE TRIGGER fin_guard_depreciation_draft_voucher
BEFORE INSERT OR UPDATE OF book_id, draft_voucher_id ON fin."depreciation"
FOR EACH ROW EXECUTE FUNCTION fin.guard_draft_voucher_reference();
CREATE TRIGGER fin_guard_invoice_draft_voucher
BEFORE INSERT OR UPDATE OF book_id, draft_voucher_id ON fin."invoice"
FOR EACH ROW EXECUTE FUNCTION fin.guard_draft_voucher_reference();
CREATE TRIGGER fin_guard_payroll_draft_voucher
BEFORE INSERT OR UPDATE OF book_id, draft_voucher_id ON fin."payroll"
FOR EACH ROW EXECUTE FUNCTION fin.guard_draft_voucher_reference();
CREATE TRIGGER fin_guard_tax_record_draft_voucher
BEFORE INSERT OR UPDATE OF book_id, draft_voucher_id ON fin."tax_record"
FOR EACH ROW EXECUTE FUNCTION fin.guard_draft_voucher_reference();
CREATE TRIGGER fin_guard_auto_entry_run_draft_voucher
BEFORE INSERT OR UPDATE OF book_id, draft_voucher_id ON fin."auto_entry_run"
FOR EACH ROW EXECUTE FUNCTION fin.guard_draft_voucher_reference();
"""


PERMISSIONS = (
    ("finance:center:view", "View finance center"),
    ("finance:voucher:write", "Create and edit finance vouchers"),
    ("finance:voucher:post", "Review and post finance vouchers"),
    ("finance:period:close", "Close and reopen finance periods"),
    ("finance:settings:write", "Manage finance settings"),
    ("finance:sensitive:view", "View sensitive finance fields"),
    ("finance:export", "Export finance records"),
)


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS fin")
    op.execute(DDL)
    op.execute(VOUCHER_GUARD_DDL)
    for code, name in PERMISSIONS:
        op.execute(
            "INSERT INTO sys.sys_permission (code, name, module, description) "
            f"VALUES ('{code}', '{name}', 'finance_center', '{MIGRATION_MARKER}') "
            "ON CONFLICT (code) DO NOTHING"
        )
    op.execute("""
        CREATE TABLE IF NOT EXISTS app.finance_center_permission_grant_backup (
            role_id bigint NOT NULL,
            permission_id bigint NOT NULL,
            PRIMARY KEY(role_id, permission_id)
        )
    """)
    op.execute("""
        INSERT INTO app.finance_center_permission_grant_backup(role_id, permission_id)
        SELECT expected.role_id, expected.permission_id
        FROM (
            SELECT r.id AS role_id, p.id AS permission_id
            FROM sys.sys_role r
            CROSS JOIN sys.sys_permission p
            WHERE r.code IN ('super_admin', 'finance_manager', 'accountant', 'cashier')
              AND p.code IN (
                  'finance:center:view',
                  'finance:voucher:write',
                  'finance:voucher:post',
                  'finance:period:close',
                  'finance:settings:write',
                  'finance:sensitive:view',
                  'finance:export'
              )
            UNION
            SELECT r.id AS role_id, p.id AS permission_id
            FROM sys.sys_role r
            CROSS JOIN sys.sys_permission p
            WHERE r.code IN ('boss', 'ceo')
              AND p.code IN (
                  'finance:center:view',
                  'finance:sensitive:view',
                  'finance:export'
              )
        ) expected
        LEFT JOIN sys.sys_role_permission existing
          ON existing.role_id = expected.role_id
         AND existing.permission_id = expected.permission_id
        WHERE existing.role_id IS NULL
        ON CONFLICT (role_id, permission_id) DO NOTHING
    """)
    op.execute("""
        INSERT INTO sys.sys_role_permission(role_id, permission_id)
        SELECT r.id, p.id
        FROM sys.sys_role r
        CROSS JOIN sys.sys_permission p
        WHERE r.code IN ('super_admin', 'finance_manager', 'accountant', 'cashier')
          AND p.code IN (
              'finance:center:view',
              'finance:voucher:write',
              'finance:voucher:post',
              'finance:period:close',
              'finance:settings:write',
              'finance:sensitive:view',
              'finance:export'
          )
        ON CONFLICT (role_id, permission_id) DO NOTHING
    """)
    op.execute("""
        INSERT INTO sys.sys_role_permission(role_id, permission_id)
        SELECT r.id, p.id
        FROM sys.sys_role r
        CROSS JOIN sys.sys_permission p
        WHERE r.code IN ('boss', 'ceo')
          AND p.code IN (
              'finance:center:view',
              'finance:sensitive:view',
              'finance:export'
          )
        ON CONFLICT (role_id, permission_id) DO NOTHING
    """)


def downgrade() -> None:
    op.execute("""
        DO $$
        BEGIN
            IF to_regclass('app.finance_center_permission_grant_backup') IS NOT NULL THEN
                DELETE FROM sys.sys_role_permission role_permission
                USING app.finance_center_permission_grant_backup backup
                WHERE role_permission.role_id = backup.role_id
                  AND role_permission.permission_id = backup.permission_id;
            END IF;
        END $$
    """)
    op.execute(
        "DELETE FROM sys.sys_permission permission "
        f"WHERE permission.description = '{MIGRATION_MARKER}' "
        "AND NOT EXISTS ("
        "SELECT 1 FROM sys.sys_role_permission role_permission "
        "WHERE role_permission.permission_id = permission.id"
        ")"
    )
    op.execute('DROP TRIGGER IF EXISTS fin_guard_voucher_entry_mutation ON fin."voucher_entry"')
    op.execute('DROP FUNCTION IF EXISTS fin.guard_voucher_entry_mutation()')
    op.execute('DROP TRIGGER IF EXISTS fin_validate_voucher ON fin."voucher"')
    op.execute('DROP FUNCTION IF EXISTS fin.validate_voucher_integrity()')
    for table_name in (
        "receivable",
        "payable",
        "settlement",
        "bank_transaction",
        "reconciliation",
        "fixed_asset",
        "depreciation",
        "invoice",
        "payroll",
        "tax_record",
        "auto_entry_run",
    ):
        op.execute(f'DROP TRIGGER IF EXISTS fin_guard_{table_name}_draft_voucher ON fin."{table_name}"')
    op.execute("DROP FUNCTION IF EXISTS fin.guard_draft_voucher_reference()")
    for table_name in reversed(TABLE_NAMES):
        op.execute(f'DROP TABLE IF EXISTS fin."{table_name}"')
    op.execute("DROP SCHEMA IF EXISTS fin")
    op.execute("DROP TABLE IF EXISTS app.finance_center_permission_grant_backup")
