"""add finance v2 voucher number reservations

Revision ID: 4f7ee5989a97
Revises: bda75497f94f
Create Date: 2026-07-29 11:31:08.376012

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "4f7ee5989a97"
down_revision = "bda75497f94f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE fin_current.voucher_number_counter (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            book_id BIGINT NOT NULL REFERENCES fin_current.accounting_book(id),
            period_id BIGINT NOT NULL REFERENCES fin_current.fiscal_period(id),
            voucher_group VARCHAR(16) NOT NULL DEFAULT '记',
            next_number INTEGER NOT NULL DEFAULT 1,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_fin_current_voucher_number_counter_scope
                UNIQUE (book_id, period_id, voucher_group),
            CONSTRAINT ck_fin_current_voucher_number_counter_next_number CHECK (next_number >= 1)
        );
        CREATE TABLE fin_current.voucher_number_reservation (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            book_id BIGINT NOT NULL REFERENCES fin_current.accounting_book(id),
            period_id BIGINT NOT NULL REFERENCES fin_current.fiscal_period(id),
            voucher_group VARCHAR(16) NOT NULL DEFAULT '记',
            voucher_no VARCHAR(64) NOT NULL,
            command_id VARCHAR(128) NOT NULL,
            status VARCHAR(16) NOT NULL DEFAULT 'reserved',
            void_reason TEXT,
            voucher_id BIGINT REFERENCES fin_current.voucher(id),
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            finalized_at TIMESTAMPTZ,
            CONSTRAINT uq_fin_current_voucher_number_reservation_scope
                UNIQUE (book_id, period_id, voucher_group, voucher_no),
            CONSTRAINT uq_fin_current_voucher_number_reservation_command UNIQUE (command_id),
            CONSTRAINT ck_fin_current_voucher_number_reservation_status
                CHECK (status IN ('reserved','used','voided')),
            CONSTRAINT ck_fin_current_voucher_number_reservation_void_reason
                CHECK (status <> 'voided' OR void_reason IS NOT NULL)
        );
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS fin_current.voucher_number_reservation")
    op.execute("DROP TABLE IF EXISTS fin_current.voucher_number_counter")
