"""Create isolated Finance V2.0 current-accounting core.

Revision ID: 7f4a8c1d9e20
Revises: 6c1e4a7d2f09
"""

from alembic import op


revision = "7f4a8c1d9e20"
down_revision = "6c1e4a7d2f09"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # This schema is deliberately separate from legacy `fin`: V2 first ships
    # read-only and must never become an accidental second formal writer.  Its
    # owner schema is provisioned by the DBA role bootstrap so this migration
    # never needs database-level CREATE privilege.
    op.execute(
        """
        DO $$
        BEGIN
            IF to_regnamespace('fin_current') IS NULL THEN
                RAISE EXCEPTION
                    'fin_current is missing; execute bootstrap_finance_database_roles.sql before Finance V2 migration';
            END IF;
        END
        $$;
        """
    )
    op.execute(
        """
        CREATE TABLE fin_current.accounting_book (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            book_code VARCHAR(64) NOT NULL UNIQUE,
            book_name VARCHAR(256) NOT NULL,
            legal_entity_name VARCHAR(256) NOT NULL,
            base_currency VARCHAR(16) NOT NULL DEFAULT 'CNY',
            history_coverage_end_date DATE,
            current_book_go_live_date DATE,
            formal_report_blocked BOOLEAN NOT NULL DEFAULT true,
            status VARCHAR(24) NOT NULL DEFAULT 'preparing',
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        CREATE TABLE fin_current.fiscal_period (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            book_id BIGINT NOT NULL REFERENCES fin_current.accounting_book(id),
            period_code VARCHAR(7) NOT NULL,
            start_date DATE NOT NULL,
            end_date DATE NOT NULL,
            status VARCHAR(16) NOT NULL DEFAULT 'open'
                CHECK (status IN ('open','closing','closed','reopening')),
            version INTEGER NOT NULL DEFAULT 1,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_fin_current_period_book_code UNIQUE (book_id, period_code),
            CONSTRAINT ck_fin_current_period_range CHECK (start_date <= end_date)
        );
        CREATE TABLE fin_current.account_version (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            book_id BIGINT NOT NULL REFERENCES fin_current.accounting_book(id),
            version_code VARCHAR(64) NOT NULL,
            account_code VARCHAR(64) NOT NULL,
            account_name VARCHAR(256) NOT NULL,
            parent_account_version_id BIGINT REFERENCES fin_current.account_version(id),
            normal_balance VARCHAR(8) NOT NULL CHECK (normal_balance IN ('debit','credit')),
            is_postable BOOLEAN NOT NULL DEFAULT true,
            effective_from DATE NOT NULL,
            effective_to DATE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_fin_current_account_version_code UNIQUE (book_id, version_code, account_code),
            CONSTRAINT ck_fin_current_account_effective_range CHECK (effective_to IS NULL OR effective_to >= effective_from)
        );
        CREATE TABLE fin_current.dimension_set (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            book_id BIGINT NOT NULL REFERENCES fin_current.accounting_book(id),
            stable_hash VARCHAR(64) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_fin_current_dimension_set_hash UNIQUE (book_id, stable_hash)
        );
        CREATE TABLE fin_current.dimension_set_item (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            dimension_set_id BIGINT NOT NULL REFERENCES fin_current.dimension_set(id),
            dimension_code VARCHAR(64) NOT NULL,
            dimension_value_code VARCHAR(128) NOT NULL,
            CONSTRAINT uq_fin_current_dimension_set_item UNIQUE (dimension_set_id, dimension_code)
        );
        CREATE TABLE fin_current.voucher (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            book_id BIGINT NOT NULL REFERENCES fin_current.accounting_book(id),
            period_id BIGINT NOT NULL REFERENCES fin_current.fiscal_period(id),
            voucher_group VARCHAR(16) NOT NULL DEFAULT '记',
            voucher_no VARCHAR(64),
            voucher_date DATE NOT NULL,
            status VARCHAR(16) NOT NULL DEFAULT 'draft'
                CHECK (status IN ('draft','submitted','reviewing','approved','rejected','cancelled','posted')),
            version INTEGER NOT NULL DEFAULT 1,
            request_id VARCHAR(128) NOT NULL,
            idempotency_key VARCHAR(128),
            prepared_by VARCHAR(128) NOT NULL,
            reviewer_id VARCHAR(128),
            approved_by VARCHAR(128),
            posted_by VARCHAR(128),
            total_debit NUMERIC(20,2) NOT NULL DEFAULT 0,
            total_credit NUMERIC(20,2) NOT NULL DEFAULT 0,
            reversal_voucher_id BIGINT REFERENCES fin_current.voucher(id),
            source_system VARCHAR(32) NOT NULL DEFAULT 'manual',
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_fin_current_voucher_request UNIQUE (book_id, request_id),
            CONSTRAINT ck_fin_current_voucher_nonnegative CHECK (total_debit >= 0 AND total_credit >= 0)
        );
        CREATE UNIQUE INDEX uq_fin_current_voucher_number
            ON fin_current.voucher(book_id, period_id, voucher_group, voucher_no)
            WHERE voucher_no IS NOT NULL;
        CREATE TABLE fin_current.voucher_line (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            voucher_id BIGINT NOT NULL REFERENCES fin_current.voucher(id),
            line_no INTEGER NOT NULL,
            account_version_id BIGINT REFERENCES fin_current.account_version(id),
            dimension_set_id BIGINT REFERENCES fin_current.dimension_set(id),
            summary VARCHAR(512) NOT NULL,
            currency_code VARCHAR(16) NOT NULL DEFAULT 'CNY',
            exchange_rate NUMERIC(20,10) NOT NULL DEFAULT 1 CHECK (exchange_rate > 0),
            debit_amount NUMERIC(20,2) NOT NULL DEFAULT 0,
            credit_amount NUMERIC(20,2) NOT NULL DEFAULT 0,
            CONSTRAINT uq_fin_current_voucher_line_no UNIQUE (voucher_id, line_no),
            CONSTRAINT ck_fin_current_voucher_line_nonnegative CHECK (debit_amount >= 0 AND credit_amount >= 0)
        );
        CREATE TABLE fin_current.ledger_balance (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            book_id BIGINT NOT NULL REFERENCES fin_current.accounting_book(id),
            period_id BIGINT NOT NULL REFERENCES fin_current.fiscal_period(id),
            account_version_id BIGINT NOT NULL REFERENCES fin_current.account_version(id),
            dimension_set_id BIGINT NOT NULL REFERENCES fin_current.dimension_set(id),
            currency_code VARCHAR(16) NOT NULL DEFAULT 'CNY',
            opening_debit NUMERIC(20,2) NOT NULL DEFAULT 0,
            opening_credit NUMERIC(20,2) NOT NULL DEFAULT 0,
            period_debit NUMERIC(20,2) NOT NULL DEFAULT 0,
            period_credit NUMERIC(20,2) NOT NULL DEFAULT 0,
            closing_debit NUMERIC(20,2) NOT NULL DEFAULT 0,
            closing_credit NUMERIC(20,2) NOT NULL DEFAULT 0,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_fin_current_ledger_balance_key UNIQUE
                (book_id, period_id, account_version_id, dimension_set_id, currency_code)
        );
        CREATE TABLE fin_current.command_idempotency (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            book_id BIGINT NOT NULL REFERENCES fin_current.accounting_book(id),
            command_name VARCHAR(64) NOT NULL,
            idempotency_key VARCHAR(128) NOT NULL,
            request_hash VARCHAR(64) NOT NULL,
            result_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
            completed_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_fin_current_command_scope_key UNIQUE (book_id, command_name, idempotency_key)
        );
        CREATE TABLE fin_current.operation_event (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            book_id BIGINT NOT NULL REFERENCES fin_current.accounting_book(id),
            voucher_id BIGINT REFERENCES fin_current.voucher(id),
            command_id VARCHAR(128) NOT NULL,
            actor_id VARCHAR(128) NOT NULL,
            action VARCHAR(64) NOT NULL,
            reason TEXT,
            before_data JSONB,
            after_data JSONB,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        """
    )
    op.execute(
        """
        CREATE FUNCTION fin_current.reject_operation_event_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'fin_current.operation_event is append-only';
        END;
        $$;
        CREATE TRIGGER tr_fin_current_operation_event_append_only
        BEFORE UPDATE OR DELETE ON fin_current.operation_event
        FOR EACH ROW EXECUTE FUNCTION fin_current.reject_operation_event_mutation();
        """
    )


def downgrade() -> None:
    op.execute("DROP SCHEMA IF EXISTS fin_current CASCADE")
