"""Add immutable Finance V2.0 historical import and published read view.

Revision ID: 8c2b5e9f1a34
Revises: 7f4a8c1d9e20
"""

from alembic import op


revision = "8c2b5e9f1a34"
down_revision = "7f4a8c1d9e20"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE SCHEMA IF NOT EXISTS fin_history;
        CREATE SCHEMA IF NOT EXISTS fin_read;
        CREATE TABLE fin_history.import_batch (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            batch_code VARCHAR(64) NOT NULL UNIQUE,
            source_system VARCHAR(32) NOT NULL DEFAULT 'kingdee',
            source_database VARCHAR(128) NOT NULL,
            status VARCHAR(16) NOT NULL DEFAULT 'created' CHECK (status IN
                ('created','loading','loaded','validating','validated','published','failed','conflicted','cancelled','superseded')),
            expected_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
            actual_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
            validation_report JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            published_at TIMESTAMPTZ
        );
        CREATE TABLE fin_history.staging_voucher (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            batch_id BIGINT NOT NULL REFERENCES fin_history.import_batch(id),
            source_system VARCHAR(32) NOT NULL,
            source_database VARCHAR(128) NOT NULL,
            source_pk VARCHAR(256) NOT NULL,
            source_hash VARCHAR(64) NOT NULL,
            payload JSONB NOT NULL,
            status VARCHAR(16) NOT NULL DEFAULT 'loaded',
            CONSTRAINT uq_fin_history_staging_source UNIQUE (batch_id, source_system, source_database, source_pk)
        );
        CREATE TABLE fin_history.voucher (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            batch_id BIGINT NOT NULL REFERENCES fin_history.import_batch(id),
            source_system VARCHAR(32) NOT NULL,
            source_database VARCHAR(128) NOT NULL,
            source_pk VARCHAR(256) NOT NULL,
            source_hash VARCHAR(64) NOT NULL,
            voucher_no VARCHAR(64), voucher_group VARCHAR(32), voucher_date DATE NOT NULL,
            fiscal_year INTEGER NOT NULL, fiscal_period INTEGER NOT NULL, source_status VARCHAR(32),
            total_debit NUMERIC(20,2) NOT NULL DEFAULT 0, total_credit NUMERIC(20,2) NOT NULL DEFAULT 0,
            is_historical BOOLEAN NOT NULL DEFAULT true,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_fin_history_voucher_source UNIQUE (source_system, source_database, source_pk)
        );
        CREATE TABLE fin_history.voucher_line (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            voucher_id BIGINT NOT NULL REFERENCES fin_history.voucher(id), line_no INTEGER NOT NULL,
            source_pk VARCHAR(256) NOT NULL, account_code VARCHAR(64), summary VARCHAR(512),
            currency_code VARCHAR(16) NOT NULL DEFAULT 'CNY', exchange_rate NUMERIC(20,10) NOT NULL DEFAULT 1,
            debit_amount NUMERIC(20,2) NOT NULL DEFAULT 0, credit_amount NUMERIC(20,2) NOT NULL DEFAULT 0,
            raw_dimensions JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_fin_history_voucher_line_no UNIQUE (voucher_id, line_no)
        );
        CREATE TABLE fin_history.source_link (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            batch_id BIGINT NOT NULL REFERENCES fin_history.import_batch(id),
            history_voucher_id BIGINT NOT NULL REFERENCES fin_history.voucher(id),
            source_system VARCHAR(32) NOT NULL, source_database VARCHAR(128) NOT NULL,
            source_pk VARCHAR(256) NOT NULL, source_hash VARCHAR(64) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_fin_history_source_link UNIQUE (source_system, source_database, source_pk)
        );
        CREATE OR REPLACE FUNCTION fin_history.reject_fact_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN RAISE EXCEPTION 'fin_history published facts are immutable'; END; $$;
        CREATE TRIGGER tr_fin_history_voucher_immutable BEFORE UPDATE OR DELETE ON fin_history.voucher
          FOR EACH ROW EXECUTE FUNCTION fin_history.reject_fact_mutation();
        CREATE TRIGGER tr_fin_history_voucher_line_immutable BEFORE UPDATE OR DELETE ON fin_history.voucher_line
          FOR EACH ROW EXECUTE FUNCTION fin_history.reject_fact_mutation();
        CREATE VIEW fin_read.history_voucher AS
          SELECT v.*, true AS historical_marker
          FROM fin_history.voucher v JOIN fin_history.import_batch b ON b.id=v.batch_id
          WHERE b.status='published';
        """
    )


def downgrade() -> None:
    op.execute("DROP SCHEMA IF EXISTS fin_read CASCADE")
    op.execute("DROP SCHEMA IF EXISTS fin_history CASCADE")
