"""add finance v2 profit closing evidence

Revision ID: 9c121d3145d9
Revises: 232ec287c52f
Create Date: 2026-07-29 16:32:12.116385

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '9c121d3145d9'
down_revision: Union[str, None] = '232ec287c52f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE fin_current.profit_closing_evidence (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            book_id BIGINT NOT NULL REFERENCES fin_current.accounting_book(id),
            period_id BIGINT NOT NULL REFERENCES fin_current.fiscal_period(id),
            voucher_id BIGINT NOT NULL REFERENCES fin_current.voucher(id),
            command_id VARCHAR(128) NOT NULL,
            confirmed_by VARCHAR(128) NOT NULL,
            reason TEXT NOT NULL,
            confirmed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_fin_current_profit_close_period UNIQUE (period_id),
            CONSTRAINT uq_fin_current_profit_close_voucher UNIQUE (voucher_id),
            CONSTRAINT uq_fin_current_profit_close_command UNIQUE (command_id),
            CONSTRAINT ck_fin_current_profit_close_reason CHECK (length(btrim(reason)) > 0)
        );
        CREATE INDEX ix_fin_current_profit_close_book_period
            ON fin_current.profit_closing_evidence (book_id, period_id);
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS fin_current.profit_closing_evidence")
