"""Add Finance V2.0 provisional and final opening balance boundary.

Revision ID: 9d3c6a0b2e45
Revises: 8c2b5e9f1a34
"""

from alembic import op


revision = "9d3c6a0b2e45"
down_revision = "8c2b5e9f1a34"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE fin_current.opening_balance_batch (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            book_id BIGINT NOT NULL REFERENCES fin_current.accounting_book(id),
            batch_kind VARCHAR(16) NOT NULL CHECK (batch_kind IN ('provisional','final')),
            status VARCHAR(16) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','validated','locked','discarded')),
            history_coverage_end_date DATE NOT NULL, go_live_date DATE NOT NULL,
            coverage_continuous BOOLEAN NOT NULL DEFAULT false, approved_by VARCHAR(128),
            approved_at TIMESTAMPTZ, locked_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_fin_current_opening_batch_scope UNIQUE (book_id, batch_kind, go_live_date),
            CONSTRAINT ck_fin_current_opening_boundary CHECK (go_live_date > history_coverage_end_date)
        );
        CREATE TABLE fin_current.opening_balance_line (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            batch_id BIGINT NOT NULL REFERENCES fin_current.opening_balance_batch(id),
            account_version_id BIGINT NOT NULL REFERENCES fin_current.account_version(id),
            dimension_set_id BIGINT NOT NULL REFERENCES fin_current.dimension_set(id),
            currency_code VARCHAR(16) NOT NULL DEFAULT 'CNY',
            debit_amount NUMERIC(20,2) NOT NULL DEFAULT 0, credit_amount NUMERIC(20,2) NOT NULL DEFAULT 0,
            source_system VARCHAR(32) NOT NULL, source_reference VARCHAR(256),
            CONSTRAINT uq_fin_current_opening_line_key UNIQUE (batch_id, account_version_id, dimension_set_id, currency_code),
            CONSTRAINT ck_fin_current_opening_line_nonnegative CHECK (debit_amount >= 0 AND credit_amount >= 0)
        );
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS fin_current.opening_balance_line")
    op.execute("DROP TABLE IF EXISTS fin_current.opening_balance_batch")
