"""add isolated Mumaren AR/AP, business and tax domains

Revision ID: a19c7e3d5b41
Revises: f8a1c4e7b2d9
"""
from typing import Sequence, Union

from alembic import op


revision: str = "a19c7e3d5b41"
down_revision: Union[str, None] = "f8a1c4e7b2d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # No old finance table, ODS/DWD object, or Kingdee source is referenced here.
    op.execute("""
    CREATE TABLE finance_center_mumaren.finance_center_mumaren_counterparties (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, book_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_books(id),
      counterparty_type VARCHAR(16) NOT NULL, counterparty_code VARCHAR(64) NOT NULL, counterparty_name VARCHAR(128) NOT NULL,
      contact VARCHAR(128), phone VARCHAR(64), tax_no VARCHAR(64), is_active BOOLEAN NOT NULL DEFAULT true,
      CONSTRAINT uq_mumaren_finance_counterparty UNIQUE(book_id,counterparty_type,counterparty_code),
      CONSTRAINT ck_mumaren_finance_counterparty_type CHECK(counterparty_type IN ('customer','supplier')));
    CREATE TABLE finance_center_mumaren.finance_center_mumaren_receivable_orders (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, book_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_books(id), order_no VARCHAR(64) NOT NULL, order_date DATE NOT NULL, period VARCHAR(7) NOT NULL, counterparty_id BIGINT, counterparty_name VARCHAR(128) NOT NULL, total_amount NUMERIC(18,2) NOT NULL DEFAULT 0, settled_amount NUMERIC(18,2) NOT NULL DEFAULT 0, settlement_status VARCHAR(16) NOT NULL DEFAULT 'open', workflow_status VARCHAR(16) NOT NULL DEFAULT 'draft', remark TEXT, created_by BIGINT, reviewed_by BIGINT, posted_by BIGINT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      CONSTRAINT uq_mumaren_finance_receivable_order UNIQUE(book_id,order_no), CONSTRAINT ck_mumaren_finance_receivable_workflow CHECK(workflow_status IN ('draft','reviewed','posted')), CONSTRAINT ck_mumaren_finance_receivable_settlement CHECK(settlement_status IN ('open','partial','settled')), CONSTRAINT ck_mumaren_finance_receivable_amount CHECK(settled_amount >= 0 AND total_amount >= 0 AND settled_amount <= total_amount));
    CREATE TABLE finance_center_mumaren.finance_center_mumaren_payable_orders (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, book_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_books(id), order_no VARCHAR(64) NOT NULL, order_date DATE NOT NULL, period VARCHAR(7) NOT NULL, counterparty_id BIGINT, counterparty_name VARCHAR(128) NOT NULL, total_amount NUMERIC(18,2) NOT NULL DEFAULT 0, settled_amount NUMERIC(18,2) NOT NULL DEFAULT 0, settlement_status VARCHAR(16) NOT NULL DEFAULT 'open', workflow_status VARCHAR(16) NOT NULL DEFAULT 'draft', remark TEXT, created_by BIGINT, reviewed_by BIGINT, posted_by BIGINT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      CONSTRAINT uq_mumaren_finance_payable_order UNIQUE(book_id,order_no), CONSTRAINT ck_mumaren_finance_payable_workflow CHECK(workflow_status IN ('draft','reviewed','posted')), CONSTRAINT ck_mumaren_finance_payable_settlement CHECK(settlement_status IN ('open','partial','settled')), CONSTRAINT ck_mumaren_finance_payable_amount CHECK(settled_amount >= 0 AND total_amount >= 0 AND settled_amount <= total_amount));
    CREATE TABLE finance_center_mumaren.finance_center_mumaren_receivable_order_lines (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_receivable_orders(id) ON DELETE CASCADE, line_no INTEGER NOT NULL, item_name VARCHAR(255) NOT NULL, spec VARCHAR(255), quantity NUMERIC(18,4) NOT NULL DEFAULT 1, unit_price NUMERIC(18,4) NOT NULL DEFAULT 0, amount NUMERIC(18,2) NOT NULL DEFAULT 0, tax_rate NUMERIC(8,4) NOT NULL DEFAULT 0, tax_amount NUMERIC(18,2) NOT NULL DEFAULT 0, remark VARCHAR(500), CONSTRAINT uq_mumaren_finance_receivable_line UNIQUE(order_id,line_no));
    CREATE TABLE finance_center_mumaren.finance_center_mumaren_payable_order_lines (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_payable_orders(id) ON DELETE CASCADE, line_no INTEGER NOT NULL, item_name VARCHAR(255) NOT NULL, spec VARCHAR(255), quantity NUMERIC(18,4) NOT NULL DEFAULT 1, unit_price NUMERIC(18,4) NOT NULL DEFAULT 0, amount NUMERIC(18,2) NOT NULL DEFAULT 0, tax_rate NUMERIC(8,4) NOT NULL DEFAULT 0, tax_amount NUMERIC(18,2) NOT NULL DEFAULT 0, remark VARCHAR(500), CONSTRAINT uq_mumaren_finance_payable_line UNIQUE(order_id,line_no));
    CREATE TABLE finance_center_mumaren.finance_center_mumaren_ar_ap_settlements (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, book_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_books(id), settlement_type VARCHAR(16) NOT NULL, order_id BIGINT NOT NULL, settlement_date DATE NOT NULL, amount NUMERIC(18,2) NOT NULL, workflow_status VARCHAR(16) NOT NULL DEFAULT 'draft', voucher_id BIGINT, remark TEXT, created_by BIGINT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), CONSTRAINT ck_mumaren_finance_settlement_type CHECK(settlement_type IN ('receivable','payable')));
    CREATE TABLE finance_center_mumaren.finance_center_mumaren_cash_accounts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, book_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_books(id), account_code VARCHAR(64) NOT NULL, account_name VARCHAR(128) NOT NULL, account_type VARCHAR(32) NOT NULL DEFAULT 'bank', currency VARCHAR(8) NOT NULL DEFAULT 'CNY', is_active BOOLEAN NOT NULL DEFAULT true, CONSTRAINT uq_mumaren_finance_cash_account UNIQUE(book_id,account_code));
    CREATE TABLE finance_center_mumaren.finance_center_mumaren_cash_flows (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, book_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_books(id), cash_account_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_cash_accounts(id), flow_date DATE NOT NULL, direction VARCHAR(8) NOT NULL, amount NUMERIC(18,2) NOT NULL, category VARCHAR(64), counterparty_name VARCHAR(128), workflow_status VARCHAR(16) NOT NULL DEFAULT 'draft', voucher_id BIGINT, remark TEXT, created_by BIGINT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), CONSTRAINT ck_mumaren_finance_cash_flow_direction CHECK(direction IN ('in','out')));
    CREATE TABLE finance_center_mumaren.finance_center_mumaren_fixed_assets (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, book_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_books(id), asset_code VARCHAR(64) NOT NULL, asset_name VARCHAR(255) NOT NULL, asset_category VARCHAR(64), purchase_date DATE NOT NULL, original_value NUMERIC(18,2) NOT NULL, residual_value NUMERIC(18,2) NOT NULL DEFAULT 0, useful_life_months INTEGER NOT NULL, accumulated_depreciation NUMERIC(18,2) NOT NULL DEFAULT 0, status VARCHAR(16) NOT NULL DEFAULT 'active', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), CONSTRAINT uq_mumaren_finance_asset UNIQUE(book_id,asset_code));
    CREATE TABLE finance_center_mumaren.finance_center_mumaren_invoices (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, book_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_books(id), invoice_no VARCHAR(64) NOT NULL, invoice_type VARCHAR(32) NOT NULL, invoice_date DATE NOT NULL, counterparty_name VARCHAR(128), amount NUMERIC(18,2) NOT NULL, tax_amount NUMERIC(18,2) NOT NULL DEFAULT 0, verification_status VARCHAR(16) NOT NULL DEFAULT 'draft', workflow_status VARCHAR(16) NOT NULL DEFAULT 'draft', CONSTRAINT uq_mumaren_finance_invoice UNIQUE(book_id,invoice_no));
    CREATE TABLE finance_center_mumaren.finance_center_mumaren_payrolls (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, book_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_books(id), period VARCHAR(7) NOT NULL, employee_no VARCHAR(64) NOT NULL, employee_name VARCHAR(128) NOT NULL, gross_amount NUMERIC(18,2) NOT NULL, deduction_amount NUMERIC(18,2) NOT NULL DEFAULT 0, net_amount NUMERIC(18,2) NOT NULL, workflow_status VARCHAR(16) NOT NULL DEFAULT 'draft', voucher_id BIGINT, CONSTRAINT uq_mumaren_finance_payroll UNIQUE(book_id,period,employee_no));
    CREATE TABLE finance_center_mumaren.finance_center_mumaren_tax_types (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, book_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_books(id), tax_code VARCHAR(64) NOT NULL, tax_name VARCHAR(128) NOT NULL, tax_category VARCHAR(64), default_rate NUMERIC(8,4) NOT NULL DEFAULT 0, is_active BOOLEAN NOT NULL DEFAULT true, CONSTRAINT uq_mumaren_finance_tax_type UNIQUE(book_id,tax_code));
    CREATE TABLE finance_center_mumaren.finance_center_mumaren_tax_records (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, book_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_books(id), tax_type_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_tax_types(id), period VARCHAR(7) NOT NULL, tax_amount NUMERIC(18,2) NOT NULL, paid_amount NUMERIC(18,2) NOT NULL DEFAULT 0, due_date DATE, status VARCHAR(16) NOT NULL DEFAULT 'pending', workflow_status VARCHAR(16) NOT NULL DEFAULT 'draft', voucher_id BIGINT, source_payload JSONB, remark TEXT, CONSTRAINT uq_mumaren_finance_tax_record UNIQUE(book_id,tax_type_id,period), CONSTRAINT ck_mumaren_finance_tax_amount CHECK(paid_amount >= 0 AND tax_amount >= 0 AND paid_amount <= tax_amount));
    CREATE INDEX ix_mumaren_finance_receivable_aging ON finance_center_mumaren.finance_center_mumaren_receivable_orders(book_id,settlement_status,order_date);
    CREATE INDEX ix_mumaren_finance_payable_aging ON finance_center_mumaren.finance_center_mumaren_payable_orders(book_id,settlement_status,order_date);
    CREATE INDEX ix_mumaren_finance_tax_due ON finance_center_mumaren.finance_center_mumaren_tax_records(book_id,status,due_date);
    """)


def downgrade() -> None:
    op.execute("""
    DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_tax_records;
    DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_tax_types;
    DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_payrolls;
    DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_invoices;
    DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_fixed_assets;
    DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_cash_flows;
    DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_cash_accounts;
    DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_ar_ap_settlements;
    DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_payable_order_lines;
    DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_receivable_order_lines;
    DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_payable_orders;
    DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_receivable_orders;
    DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_counterparties;
    """)
