"""Add Finance V2.0 feature gates and posting-attempt evidence.

Revision ID: a4e7b1c3d6f8
Revises: 9d3c6a0b2e45
"""

from alembic import op


revision = "a4e7b1c3d6f8"
down_revision = "9d3c6a0b2e45"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE fin_current.feature_gate (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            scope_type VARCHAR(16) NOT NULL CHECK (scope_type IN ('global','environment','book','source','role')),
            scope_key VARCHAR(128) NOT NULL, gate_name VARCHAR(64) NOT NULL,
            enabled BOOLEAN NOT NULL DEFAULT false, changed_by VARCHAR(128) NOT NULL, reason TEXT NOT NULL,
            approved_by VARCHAR(128), effective_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_fin_current_feature_gate_scope UNIQUE (scope_type, scope_key, gate_name)
        );
        CREATE TABLE fin_current.posting_attempt (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            voucher_id BIGINT NOT NULL REFERENCES fin_current.voucher(id), command_id VARCHAR(128) NOT NULL UNIQUE,
            status VARCHAR(16) NOT NULL DEFAULT 'running' CHECK (status IN ('running','success','failed')),
            error_code VARCHAR(64), error_context JSONB, started_at TIMESTAMPTZ NOT NULL DEFAULT now(), completed_at TIMESTAMPTZ
        );
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS fin_current.posting_attempt")
    op.execute("DROP TABLE IF EXISTS fin_current.feature_gate")
