"""add isolated Kingdee three-book migration controls

Revision ID: b19d3e5f7a01
Revises: c1d2e3f4a5b7
"""
from typing import Sequence, Union

from alembic import op


revision: str = "b19d3e5f7a01"
down_revision: Union[str, None] = "c1d2e3f4a5b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Every object in this migration belongs to the isolated finance-center schema.
    op.execute(
        """
        ALTER TABLE finance_center_mumaren.finance_center_mumaren_books
          ADD COLUMN source_system VARCHAR(32), ADD COLUMN source_database VARCHAR(128),
          ADD COLUMN source_company_name VARCHAR(255),
          ADD COLUMN source_key VARCHAR(256), ADD COLUMN source_checksum VARCHAR(64),
          ADD COLUMN import_batch_key VARCHAR(128), ADD COLUMN is_readonly BOOLEAN NOT NULL DEFAULT false;
        ALTER TABLE finance_center_mumaren.finance_center_mumaren_accounts
          ADD COLUMN source_system VARCHAR(32), ADD COLUMN source_key VARCHAR(256),
          ADD COLUMN source_checksum VARCHAR(64), ADD COLUMN import_batch_key VARCHAR(128),
          ADD COLUMN is_readonly BOOLEAN NOT NULL DEFAULT false, ADD COLUMN source_payload JSONB;
        ALTER TABLE finance_center_mumaren.finance_center_mumaren_fiscal_periods
          ADD COLUMN source_system VARCHAR(32), ADD COLUMN source_key VARCHAR(256),
          ADD COLUMN source_checksum VARCHAR(64), ADD COLUMN import_batch_key VARCHAR(128),
          ADD COLUMN is_readonly BOOLEAN NOT NULL DEFAULT false, ADD COLUMN source_payload JSONB;
        ALTER TABLE finance_center_mumaren.finance_center_mumaren_vouchers
          ADD COLUMN source_system VARCHAR(32), ADD COLUMN source_database VARCHAR(128),
          ADD COLUMN source_key VARCHAR(256), ADD COLUMN source_checksum VARCHAR(64),
          ADD COLUMN import_batch_key VARCHAR(128), ADD COLUMN is_readonly BOOLEAN NOT NULL DEFAULT false,
          ADD COLUMN is_normalized BOOLEAN NOT NULL DEFAULT false, ADD COLUMN source_payload JSONB;
        ALTER TABLE finance_center_mumaren.finance_center_mumaren_voucher_lines
          ADD COLUMN source_system VARCHAR(32), ADD COLUMN source_key VARCHAR(256),
          ADD COLUMN source_checksum VARCHAR(64), ADD COLUMN import_batch_key VARCHAR(128),
          ADD COLUMN is_readonly BOOLEAN NOT NULL DEFAULT false, ADD COLUMN source_payload JSONB;

        CREATE TABLE finance_center_mumaren.finance_center_mumaren_kingdee_import_batches (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          batch_key VARCHAR(128) NOT NULL UNIQUE,
          source_system VARCHAR(32) NOT NULL DEFAULT 'kingdee_history',
          manifest_checksum VARCHAR(64) NOT NULL,
          validation_status VARCHAR(16) NOT NULL DEFAULT 'planned',
          expected_book_count INTEGER NOT NULL,
          expected_voucher_count INTEGER NOT NULL,
          expected_line_count INTEGER NOT NULL,
          expected_balance_snapshot_count INTEGER NOT NULL,
          imported_at TIMESTAMPTZ,
          validation_payload JSONB,
          CONSTRAINT ck_mumaren_kingdee_batch_source CHECK (source_system = 'kingdee_history'),
          CONSTRAINT ck_mumaren_kingdee_batch_status CHECK (validation_status IN ('planned','validated','imported','failed'))
        );

        CREATE TABLE finance_center_mumaren.finance_center_mumaren_balance_snapshots (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          book_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_books(id),
          account_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_accounts(id),
          period_code VARCHAR(7) NOT NULL,
          source_system VARCHAR(32) NOT NULL DEFAULT 'kingdee_history',
          source_database VARCHAR(128) NOT NULL,
          source_key VARCHAR(256) NOT NULL,
          source_checksum VARCHAR(64) NOT NULL,
          import_batch_key VARCHAR(128) NOT NULL,
          is_readonly BOOLEAN NOT NULL DEFAULT true,
          opening_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
          period_debit NUMERIC(18,2) NOT NULL DEFAULT 0,
          period_credit NUMERIC(18,2) NOT NULL DEFAULT 0,
          closing_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
          source_payload JSONB,
          CONSTRAINT uq_mumaren_finance_balance_snapshot_source UNIQUE(source_system, source_database, source_key),
          CONSTRAINT ck_mumaren_finance_balance_snapshot_source CHECK (source_system = 'kingdee_history'),
          CONSTRAINT ck_mumaren_finance_balance_snapshot_readonly CHECK (is_readonly = true)
        );

        CREATE UNIQUE INDEX uq_mumaren_finance_book_kingdee_source
          ON finance_center_mumaren.finance_center_mumaren_books(source_system, source_database, source_key)
          WHERE source_system = 'kingdee_history';
        CREATE UNIQUE INDEX uq_mumaren_finance_account_kingdee_source
          ON finance_center_mumaren.finance_center_mumaren_accounts(book_id, source_system, source_key)
          WHERE source_system = 'kingdee_history';
        CREATE UNIQUE INDEX uq_mumaren_finance_period_kingdee_source
          ON finance_center_mumaren.finance_center_mumaren_fiscal_periods(book_id, source_system, source_key)
          WHERE source_system = 'kingdee_history';
        CREATE UNIQUE INDEX uq_mumaren_finance_voucher_kingdee_source
          ON finance_center_mumaren.finance_center_mumaren_vouchers(book_id, source_system, source_database, source_key)
          WHERE source_system = 'kingdee_history';
        CREATE UNIQUE INDEX uq_mumaren_finance_line_kingdee_source
          ON finance_center_mumaren.finance_center_mumaren_voucher_lines(voucher_id, source_system, source_key)
          WHERE source_system = 'kingdee_history';

        CREATE OR REPLACE FUNCTION finance_center_mumaren.assert_mumaren_writable_book(target_book_id BIGINT)
        RETURNS VOID LANGUAGE plpgsql AS $$
        BEGIN
          IF EXISTS (
            SELECT 1 FROM finance_center_mumaren.finance_center_mumaren_books
            WHERE id = target_book_id AND is_readonly = true
          ) AND coalesce(current_setting('app.mumaren_kingdee_import', true), 'off') <> 'on' THEN
            RAISE EXCEPTION 'Kingdee migrated book is permanently read-only';
          END IF;
        END;
        $$;

        CREATE OR REPLACE FUNCTION finance_center_mumaren.protect_mumaren_book()
        RETURNS TRIGGER LANGUAGE plpgsql AS $$
        BEGIN
          IF TG_OP = 'INSERT' THEN
            IF NEW.is_readonly = true AND coalesce(current_setting('app.mumaren_kingdee_import', true), 'off') <> 'on' THEN
              RAISE EXCEPTION 'readonly migrated book can only be created by migration import';
            END IF;
            RETURN NEW;
          END IF;
          PERFORM finance_center_mumaren.assert_mumaren_writable_book(OLD.id);
          RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
        END;
        $$;

        CREATE OR REPLACE FUNCTION finance_center_mumaren.protect_mumaren_book_scoped_row()
        RETURNS TRIGGER LANGUAGE plpgsql AS $$
        DECLARE target_book_id BIGINT;
        BEGIN
          target_book_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.book_id ELSE NEW.book_id END;
          PERFORM finance_center_mumaren.assert_mumaren_writable_book(target_book_id);
          RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
        END;
        $$;

        CREATE OR REPLACE FUNCTION finance_center_mumaren.protect_mumaren_voucher_line()
        RETURNS TRIGGER LANGUAGE plpgsql AS $$
        DECLARE target_voucher_id BIGINT;
        DECLARE voucher_book_id BIGINT;
        DECLARE account_book_id BIGINT;
        BEGIN
          target_voucher_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.voucher_id ELSE NEW.voucher_id END;
          SELECT book_id INTO voucher_book_id FROM finance_center_mumaren.finance_center_mumaren_vouchers WHERE id = target_voucher_id;
          PERFORM finance_center_mumaren.assert_mumaren_writable_book(voucher_book_id);
          IF TG_OP <> 'DELETE' THEN
            SELECT book_id INTO account_book_id FROM finance_center_mumaren.finance_center_mumaren_accounts WHERE id = NEW.account_id;
            IF voucher_book_id IS DISTINCT FROM account_book_id THEN
              RAISE EXCEPTION 'voucher line account must belong to the voucher book';
            END IF;
          END IF;
          RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
        END;
        $$;

        CREATE TRIGGER trg_mumaren_protect_readonly_books
          BEFORE INSERT OR UPDATE OR DELETE ON finance_center_mumaren.finance_center_mumaren_books
          FOR EACH ROW EXECUTE FUNCTION finance_center_mumaren.protect_mumaren_book();
        CREATE TRIGGER trg_mumaren_protect_readonly_accounts
          BEFORE INSERT OR UPDATE OR DELETE ON finance_center_mumaren.finance_center_mumaren_accounts
          FOR EACH ROW EXECUTE FUNCTION finance_center_mumaren.protect_mumaren_book_scoped_row();
        CREATE TRIGGER trg_mumaren_protect_readonly_periods
          BEFORE INSERT OR UPDATE OR DELETE ON finance_center_mumaren.finance_center_mumaren_fiscal_periods
          FOR EACH ROW EXECUTE FUNCTION finance_center_mumaren.protect_mumaren_book_scoped_row();
        CREATE TRIGGER trg_mumaren_protect_readonly_vouchers
          BEFORE INSERT OR UPDATE OR DELETE ON finance_center_mumaren.finance_center_mumaren_vouchers
          FOR EACH ROW EXECUTE FUNCTION finance_center_mumaren.protect_mumaren_book_scoped_row();
        CREATE TRIGGER trg_mumaren_protect_readonly_voucher_lines
          BEFORE INSERT OR UPDATE OR DELETE ON finance_center_mumaren.finance_center_mumaren_voucher_lines
          FOR EACH ROW EXECUTE FUNCTION finance_center_mumaren.protect_mumaren_voucher_line();
        CREATE TRIGGER trg_mumaren_protect_readonly_balance_snapshots
          BEFORE INSERT OR UPDATE OR DELETE ON finance_center_mumaren.finance_center_mumaren_balance_snapshots
          FOR EACH ROW EXECUTE FUNCTION finance_center_mumaren.protect_mumaren_book_scoped_row();
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DROP TRIGGER IF EXISTS trg_mumaren_protect_readonly_balance_snapshots ON finance_center_mumaren.finance_center_mumaren_balance_snapshots;
        DROP TRIGGER IF EXISTS trg_mumaren_protect_readonly_voucher_lines ON finance_center_mumaren.finance_center_mumaren_voucher_lines;
        DROP TRIGGER IF EXISTS trg_mumaren_protect_readonly_vouchers ON finance_center_mumaren.finance_center_mumaren_vouchers;
        DROP TRIGGER IF EXISTS trg_mumaren_protect_readonly_periods ON finance_center_mumaren.finance_center_mumaren_fiscal_periods;
        DROP TRIGGER IF EXISTS trg_mumaren_protect_readonly_accounts ON finance_center_mumaren.finance_center_mumaren_accounts;
        DROP TRIGGER IF EXISTS trg_mumaren_protect_readonly_books ON finance_center_mumaren.finance_center_mumaren_books;
        DROP FUNCTION IF EXISTS finance_center_mumaren.protect_mumaren_voucher_line();
        DROP FUNCTION IF EXISTS finance_center_mumaren.protect_mumaren_book_scoped_row();
        DROP FUNCTION IF EXISTS finance_center_mumaren.protect_mumaren_book();
        DROP FUNCTION IF EXISTS finance_center_mumaren.assert_mumaren_writable_book(BIGINT);
        DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_balance_snapshots;
        DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_kingdee_import_batches;
        DROP INDEX IF EXISTS finance_center_mumaren.uq_mumaren_finance_line_kingdee_source;
        DROP INDEX IF EXISTS finance_center_mumaren.uq_mumaren_finance_voucher_kingdee_source;
        DROP INDEX IF EXISTS finance_center_mumaren.uq_mumaren_finance_period_kingdee_source;
        DROP INDEX IF EXISTS finance_center_mumaren.uq_mumaren_finance_account_kingdee_source;
        DROP INDEX IF EXISTS finance_center_mumaren.uq_mumaren_finance_book_kingdee_source;
        ALTER TABLE finance_center_mumaren.finance_center_mumaren_voucher_lines
          DROP COLUMN source_payload, DROP COLUMN is_readonly, DROP COLUMN import_batch_key,
          DROP COLUMN source_checksum, DROP COLUMN source_key, DROP COLUMN source_system;
        ALTER TABLE finance_center_mumaren.finance_center_mumaren_vouchers
          DROP COLUMN source_payload, DROP COLUMN is_normalized, DROP COLUMN is_readonly,
          DROP COLUMN import_batch_key, DROP COLUMN source_checksum, DROP COLUMN source_key,
          DROP COLUMN source_database, DROP COLUMN source_system;
        ALTER TABLE finance_center_mumaren.finance_center_mumaren_fiscal_periods
          DROP COLUMN source_payload, DROP COLUMN is_readonly, DROP COLUMN import_batch_key,
          DROP COLUMN source_checksum, DROP COLUMN source_key, DROP COLUMN source_system;
        ALTER TABLE finance_center_mumaren.finance_center_mumaren_accounts
          DROP COLUMN source_payload, DROP COLUMN is_readonly, DROP COLUMN import_batch_key,
          DROP COLUMN source_checksum, DROP COLUMN source_key, DROP COLUMN source_system;
        ALTER TABLE finance_center_mumaren.finance_center_mumaren_books
          DROP COLUMN is_readonly, DROP COLUMN import_batch_key, DROP COLUMN source_checksum,
          DROP COLUMN source_key, DROP COLUMN source_company_name, DROP COLUMN source_database, DROP COLUMN source_system;
        """
    )
