"""add Mumaren daily operating settings

Revision ID: b26f2a3b4c5d
Revises: b25e1f2a3b4c

Adds isolated store groups, daily operating parameters and daily ad-cost
records.  It neither reads nor writes legacy finance, Kingdee, or Mumaren
source tables.  The existing readonly-book trigger is explicitly attached to
these later-created tables.
"""
from typing import Sequence, Union

from alembic import op


revision: str = "b26f2a3b4c5d"
down_revision: Union[str, None] = "b25e1f2a3b4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
    CREATE TABLE IF NOT EXISTS finance_center_mumaren.finance_center_mumaren_store_groups (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      book_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_books(id),
      group_name VARCHAR(128) NOT NULL,
      store_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
      created_by BIGINT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      CONSTRAINT uq_mumaren_finance_store_group UNIQUE(book_id, group_name));
    CREATE TABLE IF NOT EXISTS finance_center_mumaren.finance_center_mumaren_daily_operating_parameters (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      book_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_books(id),
      period VARCHAR(7) NOT NULL,
      store_code VARCHAR(32) NOT NULL,
      store_name VARCHAR(128),
      platform_income_rate NUMERIC(8,4) NOT NULL DEFAULT 1,
      estimated_return_rate_pct NUMERIC(8,2) NOT NULL DEFAULT 0,
      refund_only_rate_pct NUMERIC(8,2) NOT NULL DEFAULT 0,
      freight_insurance_unit_cost NUMERIC(18,4) NOT NULL DEFAULT 0,
      express_unit_cost NUMERIC(18,4) NOT NULL DEFAULT 0,
      package_unit_cost NUMERIC(18,4) NOT NULL DEFAULT 0,
      promotion_unit_cost NUMERIC(18,4) NOT NULL DEFAULT 0,
      return_labor_unit_cost NUMERIC(18,4) NOT NULL DEFAULT 0,
      goods_loss_unit_cost NUMERIC(18,4) NOT NULL DEFAULT 0,
      return_rate_warning_threshold_pct NUMERIC(8,2) NOT NULL DEFAULT 8,
      warning_enabled BOOLEAN NOT NULL DEFAULT true,
      remark TEXT,
      updated_by BIGINT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      CONSTRAINT uq_mumaren_finance_daily_operating_parameter UNIQUE(book_id, period, store_code));
    CREATE TABLE IF NOT EXISTS finance_center_mumaren.finance_center_mumaren_daily_ad_costs (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      book_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_books(id),
      business_date DATE NOT NULL,
      store_code VARCHAR(32) NOT NULL,
      store_name VARCHAR(128),
      platform VARCHAR(64),
      ad_cost NUMERIC(18,2) NOT NULL DEFAULT 0,
      compensation_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
      remark TEXT,
      updated_by BIGINT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      CONSTRAINT uq_mumaren_finance_daily_ad_cost UNIQUE(book_id, business_date, store_code));
    CREATE INDEX IF NOT EXISTS ix_mumaren_finance_daily_operating_parameter_book
      ON finance_center_mumaren.finance_center_mumaren_daily_operating_parameters(book_id, period, store_code);
    CREATE INDEX IF NOT EXISTS ix_mumaren_finance_daily_ad_cost_book
      ON finance_center_mumaren.finance_center_mumaren_daily_ad_costs(book_id, business_date, store_code);
    CREATE INDEX IF NOT EXISTS ix_mumaren_finance_store_group_book
      ON finance_center_mumaren.finance_center_mumaren_store_groups(book_id, group_name);
    DROP TRIGGER IF EXISTS trg_mumaren_protect_readonly_book_scope ON finance_center_mumaren.finance_center_mumaren_store_groups;
    CREATE TRIGGER trg_mumaren_protect_readonly_book_scope BEFORE INSERT OR UPDATE OR DELETE
      ON finance_center_mumaren.finance_center_mumaren_store_groups FOR EACH ROW
      EXECUTE FUNCTION finance_center_mumaren.protect_mumaren_book_scoped_row();
    DROP TRIGGER IF EXISTS trg_mumaren_protect_readonly_book_scope ON finance_center_mumaren.finance_center_mumaren_daily_operating_parameters;
    CREATE TRIGGER trg_mumaren_protect_readonly_book_scope BEFORE INSERT OR UPDATE OR DELETE
      ON finance_center_mumaren.finance_center_mumaren_daily_operating_parameters FOR EACH ROW
      EXECUTE FUNCTION finance_center_mumaren.protect_mumaren_book_scoped_row();
    DROP TRIGGER IF EXISTS trg_mumaren_protect_readonly_book_scope ON finance_center_mumaren.finance_center_mumaren_daily_ad_costs;
    CREATE TRIGGER trg_mumaren_protect_readonly_book_scope BEFORE INSERT OR UPDATE OR DELETE
      ON finance_center_mumaren.finance_center_mumaren_daily_ad_costs FOR EACH ROW
      EXECUTE FUNCTION finance_center_mumaren.protect_mumaren_book_scoped_row();
    """)


def downgrade() -> None:
    # Keep operational history and the readonly boundary intact.
    pass
