"""persist mumaren finance crud tables

Revision ID: c1d2e3f4a5b7
Revises: a19c7e3d5b41

Adds six isolated Mumaren finance-center CRUD tables under the
``finance_center_mumaren`` schema: voucher templates, auto-voucher rules,
expense entries, sales monthly reports, bank reconciliations and auxiliary
accounting items. No old finance table, ODS/DWD object, or Kingdee source is
referenced here.
"""
from typing import Sequence, Union

from alembic import op


revision: str = "c1d2e3f4a5b7"
down_revision: Union[str, None] = "a19c7e3d5b41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # No old finance table, ODS/DWD object, or Kingdee source is referenced here.
    op.execute("""
    CREATE TABLE finance_center_mumaren.finance_center_mumaren_voucher_templates (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      book_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_books(id),
      template_name VARCHAR(128) NOT NULL,
      voucher_type VARCHAR(16) NOT NULL DEFAULT '记',
      summary VARCHAR(500),
      lines_json JSONB,
      created_by BIGINT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      CONSTRAINT uq_mumaren_finance_voucher_template UNIQUE(book_id, template_name));
    CREATE TABLE finance_center_mumaren.finance_center_mumaren_auto_voucher_rules (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      book_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_books(id),
      rule_name VARCHAR(128) NOT NULL,
      trigger_event VARCHAR(64) NOT NULL,
      account_id BIGINT,
      direction VARCHAR(8) NOT NULL DEFAULT 'debit',
      amount_formula VARCHAR(256),
      is_active BOOLEAN NOT NULL DEFAULT true,
      created_by BIGINT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      CONSTRAINT uq_mumaren_finance_auto_voucher_rule UNIQUE(book_id, rule_name));
    CREATE TABLE finance_center_mumaren.finance_center_mumaren_expense_entries (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      book_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_books(id),
      period VARCHAR(7) NOT NULL,
      account_code VARCHAR(64) NOT NULL,
      account_name VARCHAR(128) NOT NULL,
      amount NUMERIC(18,2) NOT NULL DEFAULT 0,
      remark TEXT,
      workflow_status VARCHAR(16) NOT NULL DEFAULT 'draft',
      created_by BIGINT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      CONSTRAINT ck_mumaren_finance_expense_workflow CHECK(workflow_status IN ('draft','reviewed','posted')),
      CONSTRAINT ck_mumaren_finance_expense_amount CHECK(amount >= 0));
    CREATE TABLE finance_center_mumaren.finance_center_mumaren_sales_monthly_reports (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      book_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_books(id),
      period VARCHAR(7) NOT NULL,
      store_code VARCHAR(32) NOT NULL,
      store_name VARCHAR(128),
      sales_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
      remark TEXT,
      created_by BIGINT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      CONSTRAINT uq_mumaren_finance_sales_monthly UNIQUE(book_id, period, store_code));
    CREATE TABLE finance_center_mumaren.finance_center_mumaren_bank_reconciliations (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      book_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_books(id),
      cash_account_id BIGINT NOT NULL,
      period VARCHAR(7) NOT NULL,
      bank_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
      book_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
      adjusted_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
      items_json JSONB,
      workflow_status VARCHAR(16) NOT NULL DEFAULT 'draft',
      created_by BIGINT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      CONSTRAINT uq_mumaren_finance_bank_reconciliation UNIQUE(book_id, cash_account_id, period));
    CREATE TABLE finance_center_mumaren.finance_center_mumaren_auxiliary_accountings (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      book_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_books(id),
      aux_type VARCHAR(16) NOT NULL,
      code VARCHAR(64) NOT NULL,
      name VARCHAR(128) NOT NULL,
      parent_id BIGINT,
      is_active BOOLEAN NOT NULL DEFAULT true,
      created_by BIGINT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      CONSTRAINT uq_mumaren_finance_auxiliary_accounting UNIQUE(book_id, aux_type, code),
      CONSTRAINT ck_mumaren_finance_aux_type CHECK(aux_type IN ('customer','supplier','employee','project','department')));
    CREATE INDEX ix_mumaren_finance_voucher_template_book ON finance_center_mumaren.finance_center_mumaren_voucher_templates(book_id);
    CREATE INDEX ix_mumaren_finance_auto_voucher_rule_book ON finance_center_mumaren.finance_center_mumaren_auto_voucher_rules(book_id, trigger_event, is_active);
    CREATE INDEX ix_mumaren_finance_expense_entry_book ON finance_center_mumaren.finance_center_mumaren_expense_entries(book_id, period, workflow_status);
    CREATE INDEX ix_mumaren_finance_sales_monthly_book ON finance_center_mumaren.finance_center_mumaren_sales_monthly_reports(book_id, period);
    CREATE INDEX ix_mumaren_finance_bank_reconciliation_book ON finance_center_mumaren.finance_center_mumaren_bank_reconciliations(book_id, period);
    CREATE INDEX ix_mumaren_finance_auxiliary_accounting_book ON finance_center_mumaren.finance_center_mumaren_auxiliary_accountings(book_id, aux_type, parent_id);
    """)


def downgrade() -> None:
    op.execute("""
    DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_auxiliary_accountings;
    DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_bank_reconciliations;
    DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_sales_monthly_reports;
    DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_expense_entries;
    DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_auto_voucher_rules;
    DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_voucher_templates;
    """)
