"""add finance v2 reports and archive metadata

Revision ID: c82e5a1f9d70
Revises: 016cfd3c1454
Create Date: 2026-07-30 11:20:00.000000

"""
from typing import Sequence, Union

from alembic import op


revision: str = "c82e5a1f9d70"
down_revision: Union[str, None] = "016cfd3c1454"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE fin_current.report_template (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            book_id BIGINT NOT NULL REFERENCES fin_current.accounting_book(id),
            report_code VARCHAR(32) NOT NULL CHECK (report_code IN ('balance_sheet','profit_statement')),
            version_code VARCHAR(64) NOT NULL,
            status VARCHAR(16) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','retired')),
            effective_from DATE NOT NULL,
            effective_to DATE,
            line_definition JSONB NOT NULL,
            approved_by VARCHAR(128),
            approved_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_fin_current_report_template_version UNIQUE (book_id, report_code, version_code),
            CONSTRAINT ck_fin_current_report_template_effective_range CHECK (effective_to IS NULL OR effective_to >= effective_from),
            CONSTRAINT ck_fin_current_report_template_lines CHECK (
                jsonb_typeof(line_definition->'line_codes') = 'array'
                AND jsonb_array_length(line_definition->'line_codes') > 0
            ),
            CONSTRAINT ck_fin_current_report_template_publication_approval CHECK (
                status <> 'published' OR (approved_by IS NOT NULL AND approved_at IS NOT NULL)
            )
        );
        CREATE INDEX ix_fin_current_report_template_lookup
            ON fin_current.report_template (book_id, report_code, status, effective_from, effective_to);

        CREATE TABLE fin_current.report_mapping (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            template_id BIGINT NOT NULL REFERENCES fin_current.report_template(id),
            line_code VARCHAR(64) NOT NULL,
            account_version_id BIGINT NOT NULL REFERENCES fin_current.account_version(id),
            multiplier NUMERIC(20,10) NOT NULL CHECK (multiplier <> 0),
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_fin_current_report_mapping_line_account UNIQUE (template_id, line_code, account_version_id)
        );
        CREATE INDEX ix_fin_current_report_mapping_template ON fin_current.report_mapping (template_id);

        CREATE TABLE fin_current.report_snapshot (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            book_id BIGINT NOT NULL REFERENCES fin_current.accounting_book(id),
            period_id BIGINT NOT NULL REFERENCES fin_current.fiscal_period(id),
            template_id BIGINT NOT NULL REFERENCES fin_current.report_template(id),
            status VARCHAR(32) NOT NULL CHECK (status IN ('ready','blocked','pending_mapping','pending_data','pending_gap')),
            output_hash VARCHAR(64) NOT NULL,
            output_data JSONB NOT NULL DEFAULT '{}'::jsonb,
            generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_fin_current_report_snapshot_scope UNIQUE (book_id, period_id, template_id)
        );

        CREATE OR REPLACE FUNCTION fin_current.guard_published_report_template() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP = 'DELETE' AND OLD.status IN ('published', 'retired') THEN
                RAISE EXCEPTION 'published or retired report template cannot be deleted';
            END IF;
            IF TG_OP = 'UPDATE' AND OLD.status = 'retired' THEN
                RAISE EXCEPTION 'retired report template cannot be modified';
            END IF;
            IF TG_OP = 'UPDATE' AND OLD.status = 'published' AND NOT (
                NEW.status = 'retired'
                AND NEW.book_id = OLD.book_id AND NEW.report_code = OLD.report_code
                AND NEW.version_code = OLD.version_code AND NEW.effective_from = OLD.effective_from
                AND NEW.effective_to IS NOT DISTINCT FROM OLD.effective_to
                AND NEW.line_definition = OLD.line_definition
                AND NEW.approved_by IS NOT DISTINCT FROM OLD.approved_by
                AND NEW.approved_at IS NOT DISTINCT FROM OLD.approved_at
                AND NEW.created_at = OLD.created_at
            ) THEN
                RAISE EXCEPTION 'published report template can only be retired';
            END IF;
            IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
            RETURN NEW;
        END $$;
        CREATE TRIGGER trg_fin_current_guard_published_report_template
            BEFORE UPDATE OR DELETE ON fin_current.report_template
            FOR EACH ROW EXECUTE FUNCTION fin_current.guard_published_report_template();

        CREATE OR REPLACE FUNCTION fin_current.guard_published_report_mapping() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE target_template_id BIGINT;
        BEGIN
            target_template_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.template_id ELSE NEW.template_id END;
            IF EXISTS (SELECT 1 FROM fin_current.report_template WHERE id = target_template_id AND status <> 'draft') THEN
                RAISE EXCEPTION 'mapping of a published or retired report template cannot be modified';
            END IF;
            IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
            RETURN NEW;
        END $$;
        CREATE TRIGGER trg_fin_current_guard_published_report_mapping
            BEFORE INSERT OR UPDATE OR DELETE ON fin_current.report_mapping
            FOR EACH ROW EXECUTE FUNCTION fin_current.guard_published_report_mapping();

        CREATE OR REPLACE FUNCTION fin_current.reject_report_snapshot_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'report snapshot is immutable';
        END $$;
        CREATE TRIGGER trg_fin_current_report_snapshot_immutable
            BEFORE UPDATE OR DELETE ON fin_current.report_snapshot
            FOR EACH ROW EXECUTE FUNCTION fin_current.reject_report_snapshot_mutation();

        -- The web role reads report readiness only.  Templates, mappings and
        -- immutable snapshots are seeded or published in a controlled DBA flow.
        REVOKE INSERT, UPDATE, DELETE ON TABLE fin_current.report_template FROM fin_app;
        REVOKE INSERT, UPDATE, DELETE ON TABLE fin_current.report_mapping FROM fin_app;
        REVOKE INSERT, UPDATE, DELETE ON TABLE fin_current.report_snapshot FROM fin_app;
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DROP TRIGGER IF EXISTS trg_fin_current_report_snapshot_immutable ON fin_current.report_snapshot;
        DROP FUNCTION IF EXISTS fin_current.reject_report_snapshot_mutation();
        DROP TRIGGER IF EXISTS trg_fin_current_guard_published_report_mapping ON fin_current.report_mapping;
        DROP FUNCTION IF EXISTS fin_current.guard_published_report_mapping();
        DROP TRIGGER IF EXISTS trg_fin_current_guard_published_report_template ON fin_current.report_template;
        DROP FUNCTION IF EXISTS fin_current.guard_published_report_template();
        DROP TABLE IF EXISTS fin_current.report_snapshot;
        DROP TABLE IF EXISTS fin_current.report_mapping;
        DROP TABLE IF EXISTS fin_current.report_template;
        """
    )
