"""add finance v2 source inbox and posting rules

Revision ID: e951b2d0a6c4
Revises: c82e5a1f9d70
Create Date: 2026-07-30 13:00:00.000000

"""
from typing import Sequence, Union

from alembic import op


revision: str = "e951b2d0a6c4"
down_revision: Union[str, None] = "c82e5a1f9d70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE fin_current.source_document (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_system VARCHAR(64) NOT NULL,
            source_pk VARCHAR(256) NOT NULL,
            business_type VARCHAR(64) NOT NULL,
            legal_entity_code VARCHAR(64), organization_code VARCHAR(64),
            book_id BIGINT REFERENCES fin_current.accounting_book(id),
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_fin_current_source_document_identity UNIQUE (source_system, source_pk)
        );
        CREATE TABLE fin_current.source_document_version (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_document_id BIGINT NOT NULL REFERENCES fin_current.source_document(id),
            version_no INTEGER NOT NULL CHECK (version_no >= 1),
            source_hash VARCHAR(64) NOT NULL,
            source_occurred_at TIMESTAMPTZ,
            payload JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_fin_current_source_document_version_no UNIQUE (source_document_id, version_no),
            CONSTRAINT uq_fin_current_source_document_version_hash UNIQUE (source_document_id, source_hash)
        );
        CREATE TABLE fin_current.source_inbox (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_document_version_id BIGINT NOT NULL REFERENCES fin_current.source_document_version(id),
            status VARCHAR(32) NOT NULL DEFAULT 'received' CHECK (status IN ('received','preview_ready','pending_mapping','exception','ignored')),
            idempotency_key VARCHAR(128) NOT NULL,
            received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            last_previewed_at TIMESTAMPTZ,
            CONSTRAINT uq_fin_current_source_inbox_version UNIQUE (source_document_version_id),
            CONSTRAINT uq_fin_current_source_inbox_idempotency UNIQUE (idempotency_key)
        );
        CREATE INDEX ix_fin_current_source_inbox_status ON fin_current.source_inbox (status, received_at);

        CREATE TABLE fin_current.posting_rule (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_system VARCHAR(64) NOT NULL, rule_code VARCHAR(64) NOT NULL,
            business_type VARCHAR(64) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_fin_current_posting_rule_identity UNIQUE (source_system, rule_code)
        );
        CREATE TABLE fin_current.posting_rule_version (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            posting_rule_id BIGINT NOT NULL REFERENCES fin_current.posting_rule(id),
            version_code VARCHAR(64) NOT NULL,
            status VARCHAR(16) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','retired')),
            legal_entity_code VARCHAR(64), organization_code VARCHAR(64),
            book_id BIGINT REFERENCES fin_current.accounting_book(id),
            effective_from DATE NOT NULL, effective_to DATE,
            priority INTEGER NOT NULL DEFAULT 0,
            debit_account_version_id BIGINT NOT NULL REFERENCES fin_current.account_version(id),
            credit_account_version_id BIGINT NOT NULL REFERENCES fin_current.account_version(id),
            dimension_mapping JSONB NOT NULL DEFAULT '{}'::jsonb,
            tax_mapping JSONB NOT NULL DEFAULT '{}'::jsonb,
            published_by VARCHAR(128), published_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_fin_current_posting_rule_version_code UNIQUE (posting_rule_id, version_code),
            CONSTRAINT ck_fin_current_posting_rule_version_dates CHECK (effective_to IS NULL OR effective_to >= effective_from),
            CONSTRAINT ck_fin_current_posting_rule_version_publication CHECK (status <> 'published' OR (published_by IS NOT NULL AND published_at IS NOT NULL))
        );
        CREATE INDEX ix_fin_current_posting_rule_version_select
            ON fin_current.posting_rule_version (status, book_id, legal_entity_code, organization_code, effective_from, effective_to, priority DESC);

        CREATE TABLE fin_current.mapping_exception (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_inbox_id BIGINT NOT NULL REFERENCES fin_current.source_inbox(id),
            exception_code VARCHAR(64) NOT NULL,
            status VARCHAR(16) NOT NULL DEFAULT 'open' CHECK (status IN ('open','resolved','ignored')),
            detail JSONB NOT NULL DEFAULT '{}'::jsonb,
            resolved_by VARCHAR(128), resolved_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_fin_current_mapping_exception_inbox_code UNIQUE (source_inbox_id, exception_code)
        );
        CREATE INDEX ix_fin_current_mapping_exception_status ON fin_current.mapping_exception (status, created_at);
        CREATE TABLE fin_current.preview_run (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_inbox_id BIGINT NOT NULL REFERENCES fin_current.source_inbox(id),
            posting_rule_version_id BIGINT REFERENCES fin_current.posting_rule_version(id),
            status VARCHAR(32) NOT NULL CHECK (status IN ('preview_ready','pending_mapping','exception')),
            input_hash VARCHAR(64) NOT NULL,
            result_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
            exception_code VARCHAR(64),
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        CREATE UNIQUE INDEX uq_fin_current_preview_run_input
            ON fin_current.preview_run (source_inbox_id, COALESCE(posting_rule_version_id, 0), input_hash);

        CREATE OR REPLACE FUNCTION fin_current.guard_published_posting_rule_version() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP = 'DELETE' AND OLD.status IN ('published','retired') THEN
                RAISE EXCEPTION 'published or retired posting rule version cannot be deleted';
            END IF;
            IF TG_OP = 'UPDATE' AND OLD.status = 'retired' THEN
                RAISE EXCEPTION 'retired posting rule version cannot be modified';
            END IF;
            IF TG_OP = 'UPDATE' AND OLD.status = 'published' AND NOT (
                NEW.status = 'retired'
                AND NEW.posting_rule_id = OLD.posting_rule_id AND NEW.version_code = OLD.version_code
                AND NEW.legal_entity_code IS NOT DISTINCT FROM OLD.legal_entity_code
                AND NEW.organization_code IS NOT DISTINCT FROM OLD.organization_code
                AND NEW.book_id IS NOT DISTINCT FROM OLD.book_id
                AND NEW.effective_from = OLD.effective_from AND NEW.effective_to IS NOT DISTINCT FROM OLD.effective_to
                AND NEW.priority = OLD.priority AND NEW.debit_account_version_id = OLD.debit_account_version_id
                AND NEW.credit_account_version_id = OLD.credit_account_version_id
                AND NEW.dimension_mapping = OLD.dimension_mapping AND NEW.tax_mapping = OLD.tax_mapping
                AND NEW.published_by IS NOT DISTINCT FROM OLD.published_by AND NEW.published_at IS NOT DISTINCT FROM OLD.published_at
                AND NEW.created_at = OLD.created_at
            ) THEN
                RAISE EXCEPTION 'published posting rule version can only be retired';
            END IF;
            IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
            RETURN NEW;
        END $$;
        CREATE TRIGGER trg_fin_current_guard_published_posting_rule_version
            BEFORE UPDATE OR DELETE ON fin_current.posting_rule_version
            FOR EACH ROW EXECUTE FUNCTION fin_current.guard_published_posting_rule_version();

        -- V2.0 web APIs only inspect preview results.  Ingestion requires a
        -- separately supplied controlled identity and is not enabled by this migration.
        REVOKE INSERT, UPDATE, DELETE ON TABLE fin_current.source_document FROM fin_app;
        REVOKE INSERT, UPDATE, DELETE ON TABLE fin_current.source_document_version FROM fin_app;
        REVOKE INSERT, UPDATE, DELETE ON TABLE fin_current.source_inbox FROM fin_app;
        REVOKE INSERT, UPDATE, DELETE ON TABLE fin_current.posting_rule FROM fin_app;
        REVOKE INSERT, UPDATE, DELETE ON TABLE fin_current.posting_rule_version FROM fin_app;
        REVOKE INSERT, UPDATE, DELETE ON TABLE fin_current.mapping_exception FROM fin_app;
        REVOKE INSERT, UPDATE, DELETE ON TABLE fin_current.preview_run FROM fin_app;
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DROP TRIGGER IF EXISTS trg_fin_current_guard_published_posting_rule_version ON fin_current.posting_rule_version;
        DROP FUNCTION IF EXISTS fin_current.guard_published_posting_rule_version();
        DROP TABLE IF EXISTS fin_current.preview_run;
        DROP TABLE IF EXISTS fin_current.mapping_exception;
        DROP TABLE IF EXISTS fin_current.posting_rule_version;
        DROP TABLE IF EXISTS fin_current.posting_rule;
        DROP TABLE IF EXISTS fin_current.source_inbox;
        DROP TABLE IF EXISTS fin_current.source_document_version;
        DROP TABLE IF EXISTS fin_current.source_document;
        """
    )
