"""create isolated Mumaren finance center core

Revision ID: f8a1c4e7b2d9
Revises: e951b2d0a6c4
Create Date: 2026-07-31 10:00:00.000000

The tables in this revision deliberately live only in the
``finance_center_mumaren`` schema.  They do not reference Huabang's legacy
finance tables, Finance V2 schemas, or Kingdee source facts.
"""
from typing import Sequence, Union

from alembic import op


revision: str = "f8a1c4e7b2d9"
down_revision: Union[str, None] = "e951b2d0a6c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_PERMISSION_CODES = (
    ("mumaren_finance_center:access", "财务中心访问", "查看牧马人财务中心"),
    ("mumaren_finance_center:voucher:view", "财务凭证查看", "查看牧马人财务凭证"),
    ("mumaren_finance_center:voucher:write", "财务凭证草稿", "创建和编辑牧马人财务凭证草稿"),
    ("mumaren_finance_center:voucher:review", "财务凭证审核", "审核牧马人财务凭证"),
    ("mumaren_finance_center:voucher:post", "财务凭证人工过账", "人工过账牧马人财务凭证"),
    ("mumaren_finance_center:history:view", "历史财务查看", "查看只读金蝶历史财务记录"),
)


def upgrade() -> None:
    op.execute(
        """
        CREATE SCHEMA IF NOT EXISTS finance_center_mumaren;

        CREATE TABLE finance_center_mumaren.finance_center_mumaren_books (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            book_code VARCHAR(64) NOT NULL,
            book_name VARCHAR(128) NOT NULL,
            company_name VARCHAR(255),
            accounting_standard VARCHAR(64) NOT NULL DEFAULT '小企业会计准则',
            base_currency VARCHAR(8) NOT NULL DEFAULT 'CNY',
            status VARCHAR(16) NOT NULL DEFAULT 'active',
            created_by BIGINT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ,
            CONSTRAINT uq_mumaren_finance_book_code UNIQUE (book_code)
        );

        CREATE TABLE finance_center_mumaren.finance_center_mumaren_accounts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            book_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_books(id),
            account_code VARCHAR(64) NOT NULL,
            account_name VARCHAR(128) NOT NULL,
            account_type VARCHAR(32) NOT NULL,
            direction VARCHAR(8) NOT NULL DEFAULT 'debit',
            parent_id BIGINT,
            level INTEGER NOT NULL DEFAULT 1,
            is_active BOOLEAN NOT NULL DEFAULT true,
            CONSTRAINT uq_mumaren_finance_account_code UNIQUE (book_id, account_code)
        );
        CREATE INDEX ix_mumaren_finance_account_book ON finance_center_mumaren.finance_center_mumaren_accounts(book_id);

        CREATE TABLE finance_center_mumaren.finance_center_mumaren_fiscal_periods (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            book_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_books(id),
            period_code VARCHAR(7) NOT NULL,
            start_date DATE NOT NULL,
            end_date DATE NOT NULL,
            status VARCHAR(16) NOT NULL DEFAULT 'open',
            closed_by BIGINT,
            closed_at TIMESTAMPTZ,
            CONSTRAINT uq_mumaren_finance_period_code UNIQUE (book_id, period_code),
            CONSTRAINT ck_mumaren_finance_period_status CHECK (status IN ('open', 'closed')),
            CONSTRAINT ck_mumaren_finance_period_dates CHECK (end_date >= start_date)
        );

        CREATE TABLE finance_center_mumaren.finance_center_mumaren_vouchers (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            book_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_books(id),
            voucher_no VARCHAR(64) NOT NULL,
            voucher_type VARCHAR(16) NOT NULL DEFAULT '记',
            voucher_date DATE NOT NULL,
            summary VARCHAR(500),
            status VARCHAR(16) NOT NULL DEFAULT 'draft',
            total_debit NUMERIC(18, 2) NOT NULL DEFAULT 0,
            total_credit NUMERIC(18, 2) NOT NULL DEFAULT 0,
            created_by BIGINT,
            reviewed_by BIGINT,
            reviewed_at TIMESTAMPTZ,
            posted_by BIGINT,
            posted_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_mumaren_finance_voucher_no UNIQUE (book_id, voucher_no),
            CONSTRAINT ck_mumaren_finance_voucher_status CHECK (status IN ('draft', 'reviewed', 'posted')),
            CONSTRAINT ck_mumaren_finance_voucher_amounts CHECK (total_debit >= 0 AND total_credit >= 0)
        );
        CREATE INDEX ix_mumaren_finance_voucher_book_status ON finance_center_mumaren.finance_center_mumaren_vouchers(book_id, status, voucher_date);

        CREATE TABLE finance_center_mumaren.finance_center_mumaren_voucher_lines (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            voucher_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_vouchers(id) ON DELETE CASCADE,
            line_no INTEGER NOT NULL,
            account_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_accounts(id),
            summary VARCHAR(500),
            debit_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
            credit_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
            CONSTRAINT uq_mumaren_finance_voucher_line_no UNIQUE (voucher_id, line_no),
            CONSTRAINT ck_mumaren_finance_line_one_side CHECK (
                (debit_amount > 0 AND credit_amount = 0) OR (debit_amount = 0 AND credit_amount > 0)
            )
        );

        CREATE TABLE finance_center_mumaren.finance_center_mumaren_audit_logs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            book_id BIGINT,
            voucher_id BIGINT,
            action VARCHAR(64) NOT NULL,
            operator_id BIGINT,
            detail TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        CREATE INDEX ix_mumaren_finance_audit_voucher ON finance_center_mumaren.finance_center_mumaren_audit_logs(voucher_id, created_at);

        CREATE TABLE finance_center_mumaren.finance_center_mumaren_history_import_batches (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_system VARCHAR(32) NOT NULL DEFAULT 'kingdee',
            source_batch_key VARCHAR(128) NOT NULL,
            source_checksum VARCHAR(128),
            imported_by BIGINT,
            imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            record_count INTEGER NOT NULL DEFAULT 0,
            metadata_json JSONB,
            CONSTRAINT uq_mumaren_finance_history_batch UNIQUE (source_system, source_batch_key),
            CONSTRAINT ck_mumaren_finance_history_batch_source CHECK (source_system = 'kingdee')
        );

        CREATE TABLE finance_center_mumaren.finance_center_mumaren_history_vouchers (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            import_batch_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_history_import_batches(id),
            source_system VARCHAR(32) NOT NULL DEFAULT 'kingdee',
            source_key VARCHAR(256) NOT NULL,
            record_type VARCHAR(32) NOT NULL DEFAULT 'historical',
            is_readonly BOOLEAN NOT NULL DEFAULT true,
            voucher_no VARCHAR(64) NOT NULL,
            voucher_date DATE NOT NULL,
            summary VARCHAR(500),
            source_payload JSONB,
            imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_mumaren_finance_history_voucher UNIQUE (source_system, source_key),
            CONSTRAINT ck_mumaren_finance_history_source CHECK (source_system = 'kingdee'),
            CONSTRAINT ck_mumaren_finance_history_record_type CHECK (record_type = 'historical'),
            CONSTRAINT ck_mumaren_finance_history_readonly CHECK (is_readonly = true)
        );

        CREATE TABLE finance_center_mumaren.finance_center_mumaren_history_voucher_lines (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            history_voucher_id BIGINT NOT NULL REFERENCES finance_center_mumaren.finance_center_mumaren_history_vouchers(id) ON DELETE CASCADE,
            source_system VARCHAR(32) NOT NULL DEFAULT 'kingdee',
            source_key VARCHAR(256) NOT NULL,
            line_no INTEGER NOT NULL,
            account_code VARCHAR(64),
            account_name VARCHAR(128),
            summary VARCHAR(500),
            debit_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
            credit_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
            CONSTRAINT uq_mumaren_finance_history_voucher_line UNIQUE (history_voucher_id, source_system, source_key),
            CONSTRAINT ck_mumaren_finance_history_line_source CHECK (source_system = 'kingdee'),
            CONSTRAINT ck_mumaren_finance_history_line_one_side CHECK (
                (debit_amount >= 0 AND credit_amount >= 0) AND NOT (debit_amount > 0 AND credit_amount > 0)
            )
        );

        -- These ledgers record only rows actually inserted by this revision,
        -- so downgrade never removes a pre-existing platform permission/grant.
        CREATE TABLE finance_center_mumaren.finance_center_mumaren_permission_seed_permissions (
            permission_id BIGINT PRIMARY KEY
        );
        CREATE TABLE finance_center_mumaren.finance_center_mumaren_permission_seed_grants (
            role_id BIGINT NOT NULL,
            permission_id BIGINT NOT NULL,
            PRIMARY KEY (role_id, permission_id)
        );
        """
    )

    permission_rows = ",\n".join(
        f"('{code}', '{name}', 'mumaren_finance_center', '{description}')"
        for code, name, description in _PERMISSION_CODES
    )
    op.execute(
        f"""
        WITH inserted_permissions AS (
            INSERT INTO sys.sys_permission(code, name, module, description)
            VALUES {permission_rows}
            ON CONFLICT (code) DO NOTHING
            RETURNING id
        )
        INSERT INTO finance_center_mumaren.finance_center_mumaren_permission_seed_permissions(permission_id)
        SELECT id FROM inserted_permissions;
        """
    )

    op.execute(
        """
        WITH inserted_grants AS (
            INSERT INTO sys.sys_role_permission(role_id, permission_id)
            SELECT role.id, permission.id
            FROM sys.sys_role AS role
            CROSS JOIN sys.sys_permission AS permission
            WHERE role.code IN ('super_admin', 'finance_manager', 'finance')
              AND permission.code IN (
                  'mumaren_finance_center:access',
                  'mumaren_finance_center:voucher:view',
                  'mumaren_finance_center:voucher:write',
                  'mumaren_finance_center:voucher:review',
                  'mumaren_finance_center:voucher:post',
                  'mumaren_finance_center:history:view'
              )
            ON CONFLICT (role_id, permission_id) DO NOTHING
            RETURNING role_id, permission_id
        )
        INSERT INTO finance_center_mumaren.finance_center_mumaren_permission_seed_grants(role_id, permission_id)
        SELECT role_id, permission_id FROM inserted_grants;
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DELETE FROM sys.sys_role_permission AS role_permission
        USING finance_center_mumaren.finance_center_mumaren_permission_seed_grants AS seed_grant
        WHERE role_permission.role_id = seed_grant.role_id
          AND role_permission.permission_id = seed_grant.permission_id;
        DELETE FROM sys.sys_permission AS permission
        USING finance_center_mumaren.finance_center_mumaren_permission_seed_permissions AS seed_permission
        WHERE permission.id = seed_permission.permission_id
          AND NOT EXISTS (
              SELECT 1 FROM sys.sys_role_permission AS role_permission
              WHERE role_permission.permission_id = permission.id
          );

        DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_permission_seed_grants;
        DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_permission_seed_permissions;
        DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_history_voucher_lines;
        DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_history_vouchers;
        DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_history_import_batches;
        DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_audit_logs;
        DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_voucher_lines;
        DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_vouchers;
        DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_fiscal_periods;
        DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_accounts;
        DROP TABLE IF EXISTS finance_center_mumaren.finance_center_mumaren_books;
        DROP SCHEMA IF EXISTS finance_center_mumaren;
        """
    )
