<template>
  <section class="panel">
    <div class="heading"><div><p class="panel-kicker">经营设置</p><h2>每日经营参数</h2><p>仅维护日报计算参数，不自动生成凭证；按独立账簿隔离。</p></div><div class="actions"><el-button :loading="loading" :disabled="!bookId" @click="load">刷新</el-button><el-button :disabled="!bookId || isReadonly" @click="groupVisible = true">管理店铺组</el-button><el-button :disabled="!bookId || isReadonly" @click="fileInput?.click()">从表格导入数据</el-button><el-button :disabled="!bookId || isReadonly" @click="copyPrevious">复制上月参数</el-button><el-button type="primary" :disabled="!bookId || isReadonly" :loading="saving" @click="saveAll">保存全部</el-button></div></div>
    <input ref="fileInput" type="file" accept=".csv,text/csv" hidden @change="importCsv" />
    <div class="filters"><el-select v-model="bookId" placeholder="选择独立账簿" clearable><el-option v-for="book in books" :key="book.id" :label="book.book_name" :value="book.id" /></el-select><el-date-picker v-model="period" type="month" value-format="YYYY-MM" placeholder="月份" /><el-select v-model="selectedGroup" clearable placeholder="全部店铺组"><el-option v-for="group in groups" :key="group.id" :label="group.group_name" :value="group.id" /></el-select><el-button :disabled="!bookId || isReadonly || !visibleRows.length" @click="openBatch">批量维护参数</el-button></div>
    <el-alert type="info" :closable="false" title="表格导入支持 CSV：首列必须为 store_code；其余列可使用页面字段名。Excel 可另存为 CSV 后导入。" />
    <el-alert v-if="isReadonly" type="warning" :closable="false" show-icon title="金蝶迁移账簿只读，不能维护经营参数。" />
    <el-alert v-if="error" type="error" :closable="false" :title="error" show-icon />
    <el-table :data="visibleRows" v-loading="loading" border stripe size="small" empty-text="请选择独立账簿"><el-table-column prop="store_code" label="店铺编码" width="108" fixed /><el-table-column prop="store_name" label="店铺名称" width="150"><template #default="{ row }"><el-input v-model="row.store_name" :disabled="isReadonly" size="small" /></template></el-table-column><el-table-column v-for="field in fields" :key="field.key" :label="field.label" width="136" align="right"><template #default="{ row }"><el-input-number v-model="row[field.key]" :disabled="isReadonly" :min="0" :max="field.max" :precision="field.precision" :controls="false" size="small" style="width:112px" /></template></el-table-column><el-table-column label="预警" width="70"><template #default="{ row }"><el-switch v-model="row.warning_enabled" :disabled="isReadonly" /></template></el-table-column><el-table-column label="备注" min-width="140"><template #default="{ row }"><el-input v-model="row.remark" :disabled="isReadonly" size="small" /></template></el-table-column></el-table>

    <el-dialog v-model="batchVisible" title="批量维护参数" width="420px"><el-form label-width="100px"><el-form-item label="字段"><el-select v-model="batch.field" style="width:100%"><el-option v-for="field in fields" :key="field.key" :label="field.label" :value="field.key" /></el-select></el-form-item><el-form-item label="数值"><el-input-number v-model="batch.value" :min="0" :precision="4" style="width:100%" /></el-form-item><el-form-item label="作用范围"><span>{{ visibleRows.length }} 家店铺</span></el-form-item></el-form><template #footer><el-button @click="batchVisible = false">取消</el-button><el-button type="primary" :loading="batching" @click="applyBatch">应用</el-button></template></el-dialog>
    <el-dialog v-model="groupVisible" title="管理店铺组" width="560px"><el-table :data="groups" size="small" empty-text="暂无店铺组"><el-table-column prop="group_name" label="名称" /><el-table-column label="店铺编码"><template #default="{ row }">{{ row.store_codes.join('、') }}</template></el-table-column><el-table-column width="70"><template #default="{ row }"><el-button link type="danger" :disabled="isReadonly" @click="removeGroup(row.id)">删除</el-button></template></el-table-column></el-table><el-divider /><el-form :model="groupForm" label-width="78px"><el-form-item label="组名"><el-input v-model="groupForm.group_name" maxlength="128" /></el-form-item><el-form-item label="店铺编码"><el-input v-model="groupForm.store_codes" placeholder="以逗号分隔，例如 285101,285102" /></el-form-item></el-form><template #footer><el-button @click="groupVisible = false">关闭</el-button><el-button type="primary" :disabled="isReadonly" :loading="groupSaving" @click="saveGroup">新增店铺组</el-button></template></el-dialog>
  </section>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from "vue";
import { ElMessage } from "element-plus";
import { useMumarenFinanceBook } from "@/composables/useMumarenFinanceBook";
import { operatingSettingsApi, type MumarenDailyOperatingParameter, type MumarenOperatingStoreGroup } from "@/api/mumarenFinanceCenter";

const { books, bookId, isReadonly, loadBooks } = useMumarenFinanceBook();
const period = ref(new Date().toISOString().slice(0, 7));
const rows = ref<MumarenDailyOperatingParameter[]>([]); const groups = ref<MumarenOperatingStoreGroup[]>([]); const selectedGroup = ref<number>();
const loading = ref(false); const saving = ref(false); const batching = ref(false); const groupSaving = ref(false); const error = ref("");
const fileInput = ref<HTMLInputElement>(); const batchVisible = ref(false); const groupVisible = ref(false);
const batch = reactive({ field: "platform_income_rate", value: 0 }); const groupForm = reactive({ group_name: "", store_codes: "" });
let loadRequestVersion = 0;
const fields = [
  { key: "platform_income_rate", label: "平台收入系数", max: 2, precision: 4 }, { key: "estimated_return_rate_pct", label: "预估退货率(%)", max: 100, precision: 2 }, { key: "refund_only_rate_pct", label: "仅退款率(%)", max: 100, precision: 2 },
  { key: "freight_insurance_unit_cost", label: "运费险/件", max: 1000000, precision: 4 }, { key: "express_unit_cost", label: "快递费/件", max: 1000000, precision: 4 }, { key: "package_unit_cost", label: "包装费/单", max: 1000000, precision: 4 },
  { key: "promotion_unit_cost", label: "推广单件", max: 1000000, precision: 4 }, { key: "return_labor_unit_cost", label: "退货人工/件", max: 1000000, precision: 4 }, { key: "goods_loss_unit_cost", label: "货值损耗/件", max: 1000000, precision: 4 }, { key: "return_rate_warning_threshold_pct", label: "退货预警(%)", max: 100, precision: 2 },
] as const;
const visibleRows = computed(() => { const group = groups.value.find((item) => item.id === selectedGroup.value); return group ? rows.value.filter((row) => group.store_codes.includes(row.store_code)) : rows.value; });
const load = async () => { const requestedBookId = bookId.value; const requestedPeriod = period.value; const requestVersion = ++loadRequestVersion; if (!requestedBookId) { rows.value = []; groups.value = []; loading.value = false; error.value = ""; return; } loading.value = true; error.value = ""; try { const [parameters, storeGroups] = await Promise.all([operatingSettingsApi.listDailyParameters({ book_id: requestedBookId, period: requestedPeriod }), operatingSettingsApi.listStoreGroups({ book_id: requestedBookId })]); if (requestVersion !== loadRequestVersion || requestedBookId !== bookId.value || requestedPeriod !== period.value) return; rows.value = parameters.data.data; groups.value = storeGroups.data.data; } catch (e: any) { if (requestVersion === loadRequestVersion && requestedBookId === bookId.value && requestedPeriod === period.value) error.value = e?.response?.data?.detail || "无法加载每日经营参数。"; } finally { if (requestVersion === loadRequestVersion) loading.value = false; } };
const saveAll = async () => { if (!bookId.value || isReadonly.value) return; saving.value = true; try { await operatingSettingsApi.saveDailyParameters({ book_id: bookId.value, period: period.value, rows: rows.value.map(({ book_id, period: _period, id, updated_at, ...row }) => row) }); ElMessage.success("每日经营参数已保存"); await load(); } catch (e: any) { ElMessage.error(e?.response?.data?.detail || "保存失败"); } finally { saving.value = false; } };
const copyPrevious = async () => { if (!bookId.value || isReadonly.value) return; try { const result = await operatingSettingsApi.copyPreviousDailyParameters({ book_id: bookId.value, period: period.value }); ElMessage.success(`已复制上月 ${result.data.data.copied_count} 条参数`); await load(); } catch (e: any) { ElMessage.error(e?.response?.data?.detail || "复制失败"); } };
const openBatch = () => { batch.field = "platform_income_rate"; batch.value = 0; batchVisible.value = true; };
const applyBatch = async () => { if (!bookId.value || isReadonly.value || !visibleRows.value.length) return; batching.value = true; try { await operatingSettingsApi.batchDailyParameter({ book_id: bookId.value, period: period.value, field: batch.field, value: batch.value, store_codes: visibleRows.value.map((row) => row.store_code) }); ElMessage.success("批量参数已应用"); batchVisible.value = false; await load(); } catch (e: any) { ElMessage.error(e?.response?.data?.detail || "批量维护失败"); } finally { batching.value = false; } };
const saveGroup = async () => { if (!bookId.value || isReadonly.value) return; const store_codes = groupForm.store_codes.split(/[,，\s]+/).filter(Boolean); if (!groupForm.group_name.trim() || !store_codes.length) return ElMessage.warning("请填写组名和店铺编码"); groupSaving.value = true; try { await operatingSettingsApi.createStoreGroup({ book_id: bookId.value, group_name: groupForm.group_name.trim(), store_codes }); groupForm.group_name = ""; groupForm.store_codes = ""; await load(); } catch (e: any) { ElMessage.error(e?.response?.data?.detail || "保存店铺组失败"); } finally { groupSaving.value = false; } };
const removeGroup = async (id: number) => { if (!bookId.value || isReadonly.value) return; try { await operatingSettingsApi.deleteStoreGroup(id, bookId.value); if (selectedGroup.value === id) selectedGroup.value = undefined; await load(); } catch (e: any) { ElMessage.error(e?.response?.data?.detail || "删除失败"); } };
const csvCells = (line: string) => { const result: string[] = []; let value = "", quoted = false; for (let i = 0; i < line.length; i += 1) { const char = line[i]; if (char === '"') { if (quoted && line[i + 1] === '"') { value += char; i += 1; } else quoted = !quoted; } else if (char === ',' && !quoted) { result.push(value.trim()); value = ""; } else value += char; } result.push(value.trim()); return result; };
const importCsv = async (event: Event) => { const file = (event.target as HTMLInputElement).files?.[0]; if (!file || !bookId.value || isReadonly.value) return; try { const text = await file.text(); const [headerLine, ...lines] = text.replace(/^\uFEFF/, "").split(/\r?\n/).filter(Boolean); const headers = csvCells(headerLine); if (!headers.includes("store_code")) throw new Error("CSV 必须包含 store_code 列"); const imported = lines.map((line) => Object.fromEntries(headers.map((header, index) => [header, csvCells(line)[index] || ""]))); for (const item of imported) { const target = rows.value.find((row) => row.store_code === String(item.store_code).toUpperCase()); if (!target) continue; target.store_name = item.store_name || target.store_name; for (const field of fields) if (item[field.key] !== "" && item[field.key] !== undefined) (target as any)[field.key] = Number(item[field.key]); if (item.warning_enabled !== "" && item.warning_enabled !== undefined) target.warning_enabled = ["true", "1", "是"].includes(String(item.warning_enabled).toLowerCase()); if (item.remark !== undefined) target.remark = item.remark || null; } ElMessage.success("CSV 已载入页面，请点击保存全部确认写入"); } catch (e: any) { ElMessage.error(e?.message || "导入失败"); } finally { (event.target as HTMLInputElement).value = ""; } };
watch([bookId, period], load); onMounted(async () => { await loadBooks(); await load(); });
</script>

<style scoped>.panel { padding:30px; border:1px solid #e1e7ef; border-radius:14px; background:#fff; display:grid; gap:16px; }.heading,.actions,.filters { display:flex; gap:10px; align-items:center; flex-wrap:wrap; }.heading{justify-content:space-between;align-items:flex-start}.panel-kicker{margin:0;color:#176b97;font-size:12px;font-weight:700;letter-spacing:.08em}h2{margin:8px 0}p{color:#5d6b7e}@media(max-width:640px){.heading{flex-direction:column}.actions{width:100%}}</style>
