<template>
  <section class="panel"><div class="heading"><div><p class="panel-kicker">经营与财务</p><h2>报表</h2><p>仅按独立当前账已过账凭证计算，不混入历史归档。</p></div><el-button :loading="loading" :disabled="!bookId" @click="load">查询</el-button></div>
    <div class="filters"><el-select v-model="bookId" placeholder="选择账簿" clearable><el-option v-for="book in books" :key="book.id" :label="book.book_name" :value="book.id" /></el-select><el-input v-model="period" placeholder="期间，如 2026-07（可选）" /></div>
    <el-alert v-if="error" type="error" :title="error" :closable="false" show-icon />
    <template v-else><el-descriptions title="利润表" :column="3" border><el-descriptions-item label="收入">{{ money(profit.total_income) }}</el-descriptions-item><el-descriptions-item label="费用">{{ money(profit.total_expense) }}</el-descriptions-item><el-descriptions-item label="净利润">{{ money(profit.net_profit) }}</el-descriptions-item></el-descriptions><el-table :data="trialRows" empty-text="暂无已过账数据" stripe><el-table-column prop="account_code" label="科目编码" /><el-table-column prop="account_name" label="科目名称" min-width="180" /><el-table-column prop="debit_amount" label="借方" align="right"><template #default="scope">{{ money(scope.row.debit_amount) }}</template></el-table-column><el-table-column prop="credit_amount" label="贷方" align="right"><template #default="scope">{{ money(scope.row.credit_amount) }}</template></el-table-column></el-table></template>
  </section>
</template>
<script setup lang="ts">
import { onMounted, ref } from "vue"; import { mumarenFinanceCenterApi, type MumarenFinanceBook, type MumarenProfitStatement, type MumarenTrialBalanceRow } from "@/api/mumarenFinanceCenter";
const books = ref<MumarenFinanceBook[]>([]); const bookId = ref<number>(); const period = ref(""); const trialRows = ref<MumarenTrialBalanceRow[]>([]); const profit = ref<Partial<MumarenProfitStatement>>({}); const error = ref(""); const loading = ref(false); const money = (value?: number) => new Intl.NumberFormat("zh-CN", { minimumFractionDigits:2, maximumFractionDigits:2 }).format(value || 0);
const load = async () => { if (!bookId.value) return; loading.value=true; error.value=""; try { const params={ book_id:bookId.value, period:period.value || undefined }; const [trial, statement]=await Promise.all([mumarenFinanceCenterApi.getTrialBalance(params), mumarenFinanceCenterApi.getProfitStatement(params)]); trialRows.value=trial.data.data.rows || []; profit.value=statement.data.data; } catch { error.value="无法加载独立当前账报表。"; } finally { loading.value=false; } };
onMounted(async () => { try { books.value=(await mumarenFinanceCenterApi.listBooks()).data.data; bookId.value=books.value[0]?.id; if (bookId.value) await load(); } catch { error.value="无法加载独立账簿。"; } });
</script>
<style scoped>.panel { padding:30px; border:1px solid #e1e7ef; border-radius:14px; background:#fff; display:grid; gap:16px; }.heading { display:flex; justify-content:space-between; gap:16px; align-items:flex-start; }.filters { display:flex; gap:12px; }.filters>* { max-width:280px; }.panel-kicker { margin:0; color:#176b97; font-size:12px; font-weight:700; letter-spacing:.08em; }h2 { margin:8px 0; }p { color:#5d6b7e; }@media(max-width:640px){.filters{flex-direction:column}.filters>*{max-width:none}}</style>
