<template>
  <section class="panel">
    <div class="heading"><div><p class="panel-kicker">凭证管理</p><h2>自动凭证</h2><p>{{ isReadonly ? "金蝶迁移账簿未导入自动凭证规则；请查询原始凭证、明细账和余额快照。" : "规则仅生成平衡草稿；财务人员审核后，仍须人工过账。" }}</p></div><div class="heading-actions"><el-button :disabled="!bookId" :loading="loading" @click="load">刷新</el-button><el-button type="primary" :disabled="!bookId || isReadonly" @click="openEditor()">新增规则</el-button></div></div>
    <el-select v-model="bookId" placeholder="选择独立账簿" clearable class="book-select"><el-option v-for="book in books" :key="book.id" :label="book.book_name" :value="book.id" /></el-select>
    <el-alert v-if="error" type="error" :title="error" :closable="false" show-icon />
    <el-alert v-if="isReadonly" type="warning" title="金蝶迁移账簿未导入自动凭证规则，当前页面不以空表表示历史规则为零。" :closable="false" show-icon />
    <el-table v-if="!isReadonly" v-loading="loading" :data="rules" empty-text="暂无自动凭证规则" stripe>
      <el-table-column prop="rule_name" label="规则名称" min-width="150" /><el-table-column prop="trigger_event" label="触发场景" min-width="130" />
      <el-table-column label="借方科目" min-width="150"><template #default="{ row }">{{ accountLabel(row.debit_account_id) }}</template></el-table-column>
      <el-table-column label="贷方科目" min-width="150"><template #default="{ row }">{{ accountLabel(row.credit_account_id) }}</template></el-table-column>
      <el-table-column label="默认金额" width="120"><template #default="{ row }">{{ row.default_amount ? `¥${money(row.default_amount)}` : "执行时填写" }}</template></el-table-column>
      <el-table-column label="状态" width="90"><template #default="{ row }"><el-tag :type="row.is_active ? 'success' : 'info'" size="small">{{ row.is_active ? "启用" : "停用" }}</el-tag></template></el-table-column>
      <el-table-column label="操作" width="240"><template #default="{ row }"><el-button link type="primary" :disabled="isReadonly || !row.is_active" @click="openRun(row)">生成凭证草稿</el-button><el-button link :disabled="isReadonly" @click="openEditor(row)">编辑</el-button><el-popconfirm title="确定删除该规则吗?" @confirm="removeRow(row)"><template #reference><el-button link type="danger" :disabled="isReadonly">删除</el-button></template></el-popconfirm></template></el-table-column>
    </el-table>
    <el-dialog v-model="editorVisible" :title="editingRule ? '编辑规则' : '新增规则'" width="600px"><el-form ref="formRef" :model="form" :rules="formRules" label-width="100px"><el-form-item label="规则名称" prop="rule_name"><el-input v-model="form.rule_name" /></el-form-item><el-form-item label="触发场景" prop="trigger_event"><el-select v-model="form.trigger_event" style="width:100%"><el-option label="月度销售" value="sales_monthly"/><el-option label="月度薪酬" value="payroll_monthly"/><el-option label="折旧摊销" value="depreciation_monthly"/><el-option label="人工调整" value="manual_adjustment"/></el-select></el-form-item><el-form-item label="借方科目" prop="debit_account_id"><el-select v-model="form.debit_account_id" filterable style="width:100%"><el-option v-for="item in accounts" :key="item.id" :label="`${item.account_code} ${item.account_name}`" :value="item.id"/></el-select></el-form-item><el-form-item label="贷方科目" prop="credit_account_id"><el-select v-model="form.credit_account_id" filterable style="width:100%"><el-option v-for="item in accounts" :key="item.id" :label="`${item.account_code} ${item.account_name}`" :value="item.id"/></el-select></el-form-item><el-form-item label="默认金额"><el-input-number v-model="form.default_amount" :min="0.01" :precision="2" style="width:100%"/></el-form-item><el-form-item label="摘要"><el-input v-model="form.summary"/></el-form-item><el-form-item label="凭证字"><el-input v-model="form.voucher_type" maxlength="16"/></el-form-item><el-form-item label="启用"><el-switch v-model="form.is_active"/></el-form-item></el-form><template #footer><el-button @click="editorVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="submitRule">保存</el-button></template></el-dialog>
    <el-dialog v-model="runVisible" title="生成凭证草稿" width="600px"><el-alert type="info" :closable="false" title="此操作只会创建草稿，不会审核或过账。相同来源标识重复提交将返回已生成的草稿。"/><el-form ref="runFormRef" :model="runForm" :rules="runRules" label-width="100px" class="run-form"><el-form-item label="凭证号" prop="voucher_no"><el-input v-model="runForm.voucher_no"/></el-form-item><el-form-item label="凭证日期" prop="voucher_date"><el-date-picker v-model="runForm.voucher_date" value-format="YYYY-MM-DD" type="date" style="width:100%"/></el-form-item><el-form-item label="来源标识" prop="source_key"><el-input v-model="runForm.source_key" placeholder="例如 2026-08-销售汇总"/></el-form-item><el-form-item label="金额"><el-input-number v-model="runForm.amount" :min="0.01" :precision="2" style="width:100%"/></el-form-item><el-form-item label="摘要"><el-input v-model="runForm.summary" placeholder="留空使用规则摘要"/></el-form-item></el-form><div v-if="preview" class="preview"><strong>预览：借贷平衡 ¥{{ money(preview.amount) }}</strong><div v-for="line in preview.lines" :key="line.account_id">{{ accountLabel(line.account_id) }}：借 {{ money(line.debit_amount) }} / 贷 {{ money(line.credit_amount) }}</div></div><template #footer><el-button :loading="previewing" @click="previewDraft">预览</el-button><el-button type="primary" :loading="generating" @click="generateDraft">生成凭证草稿</el-button></template></el-dialog>
  </section>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from "vue";
import { ElMessage, type FormInstance, type FormRules } from "element-plus";
import { autoVoucherRulesApi, mumarenFinanceCenterApi, type AutoVoucherDraftPreview, type MumarenAutoVoucherRule } from "@/api/mumarenFinanceCenter";
import { useMumarenFinanceBook } from "@/composables/useMumarenFinanceBook";
const { books, bookId, isReadonly, loadBooks } = useMumarenFinanceBook(); const rules=ref<MumarenAutoVoucherRule[]>([]); const accounts=ref<any[]>([]); const loading=ref(false); const saving=ref(false); const generating=ref(false); const previewing=ref(false); const error=ref(""); const editorVisible=ref(false); const runVisible=ref(false); const editingRule=ref<MumarenAutoVoucherRule|null>(null); const runRule=ref<MumarenAutoVoucherRule|null>(null); const preview=ref<AutoVoucherDraftPreview|null>(null); const formRef=ref<FormInstance>(); const runFormRef=ref<FormInstance>(); let version=0;
const form=reactive<any>({rule_name:"",trigger_event:"sales_monthly",debit_account_id:null,credit_account_id:null,default_amount:undefined,summary:"",voucher_type:"记",is_active:true}); const runForm=reactive<any>({voucher_no:"",voucher_date:new Date().toISOString().slice(0,10),source_key:"",amount:undefined,summary:""});
const formRules:FormRules={rule_name:[{required:true,message:"请输入规则名称",trigger:"blur"}],trigger_event:[{required:true,message:"请选择触发场景",trigger:"change"}],debit_account_id:[{required:true,message:"请选择借方科目",trigger:"change"}],credit_account_id:[{required:true,message:"请选择贷方科目",trigger:"change"}]}; const runRules:FormRules={voucher_no:[{required:true,message:"请输入凭证号",trigger:"blur"}],voucher_date:[{required:true,message:"请选择日期",trigger:"change"}],source_key:[{required:true,message:"请输入来源标识",trigger:"blur"}]};
const money=(value:number)=>new Intl.NumberFormat("zh-CN",{minimumFractionDigits:2,maximumFractionDigits:2}).format(value||0); const accountMap=computed(()=>new Map(accounts.value.map(a=>[a.id,`${a.account_code} ${a.account_name}`]))); const accountLabel=(id:number|null)=>id?accountMap.value.get(id)||`科目 #${id}`:"未配置";
async function load(){const requested=bookId.value; const id=++version; rules.value=[];accounts.value=[]; if(!requested){loading.value=false;error.value="";return;} if(isReadonly.value){loading.value=false;error.value="";return;} loading.value=true;error.value="";try{const [ruleResult,accountResult]=await Promise.all([autoVoucherRulesApi.list({book_id:requested}),mumarenFinanceCenterApi.listAccounts(requested)]);if(id===version&&bookId.value===requested&&!isReadonly.value){rules.value=ruleResult.data.data;accounts.value=accountResult.data.data;}}catch{if(id===version&&bookId.value===requested&&!isReadonly.value)error.value="无法加载自动凭证规则或会计科目。";}finally{if(id===version)loading.value=false;}}
watch(bookId,()=>{editorVisible.value=false;runVisible.value=false;load();}); onMounted(async()=>{try{await loadBooks();await load();}catch{error.value="无法加载独立账簿。";}});
function openEditor(row?:MumarenAutoVoucherRule){if(!bookId.value||isReadonly.value)return;editingRule.value=row||null;Object.assign(form,row?{...row}:{rule_name:"",trigger_event:"sales_monthly",debit_account_id:null,credit_account_id:null,default_amount:undefined,summary:"",voucher_type:"记",is_active:true});editorVisible.value=true;}
async function submitRule(){if(!bookId.value||isReadonly.value||!formRef.value)return;await formRef.value.validate(async valid=>{if(!valid)return;if(form.debit_account_id===form.credit_account_id){ElMessage.error("借方和贷方科目不能相同");return;}saving.value=true;try{const data={...form,book_id:bookId.value,rule_name:form.rule_name.trim(),summary:form.summary?.trim()||undefined};if(editingRule.value)await autoVoucherRulesApi.update(editingRule.value.id,data);else await autoVoucherRulesApi.create(data);ElMessage.success("规则已保存");editorVisible.value=false;await load();}catch(e:any){ElMessage.error(e?.response?.data?.detail||"保存失败");}finally{saving.value=false;}})}
function openRun(row:MumarenAutoVoucherRule){runRule.value=row;preview.value=null;Object.assign(runForm,{voucher_no:"",voucher_date:new Date().toISOString().slice(0,10),source_key:"",amount:row.default_amount||undefined,summary:row.summary||""});runVisible.value=true;} function requestBody(){return {...runForm,book_id:bookId.value!,summary:runForm.summary?.trim()||undefined};}
async function previewDraft(){if(!runRule.value||!runFormRef.value)return;await runFormRef.value.validate(async valid=>{if(!valid)return;previewing.value=true;try{preview.value=(await autoVoucherRulesApi.previewAutoVoucherDraft(runRule.value!.id,requestBody())).data.data;}catch(e:any){ElMessage.error(e?.response?.data?.detail||"预览失败");}finally{previewing.value=false;}})}
async function generateDraft(){if(!runRule.value||!runFormRef.value||isReadonly.value)return;await runFormRef.value.validate(async valid=>{if(!valid)return;generating.value=true;try{const result=(await autoVoucherRulesApi.generateAutoVoucherDraft(runRule.value!.id,requestBody())).data.data;ElMessage.success(result.reused?"已返回此前生成的草稿":"草稿已生成，请到凭证列表审核");runVisible.value=false;}catch(e:any){ElMessage.error(e?.response?.data?.detail||"生成草稿失败");}finally{generating.value=false;}})}
async function removeRow(row:MumarenAutoVoucherRule){if(!bookId.value||isReadonly.value)return;try{await autoVoucherRulesApi.delete(row.id,bookId.value);ElMessage.success("规则已删除");await load();}catch(e:any){ElMessage.error(e?.response?.data?.detail||"删除失败");}}
</script>
<style scoped>.panel{padding:30px;border:1px solid #e1e7ef;border-radius:14px;background:#fff;display:grid;gap:16px}.heading{display:flex;justify-content:space-between;gap:16px}.heading-actions{display:flex;gap:8px}.panel-kicker{margin:0;color:#176b97;font-size:12px;font-weight:700}h2{margin:8px 0}.book-select{max-width:300px}.run-form{margin-top:16px}.preview{padding:12px;background:#f5f8fc;line-height:1.9;color:#425466}@media(max-width:640px){.heading{flex-direction:column}}</style>
